<header>
	<div class="top-half outer">
		<div class="row content-between">
			<div class="col-flexible">
				<ul class="apps">
					<li class="selected"><a href="<?= $community_url ?>">Community</a></li>
					<li><a href="articles">Articles</a></li>
					<?php if($website_url != "" && $website_url != "http://"): ?>
						<li><a href="<?= $website_url ?>" target="_blank"><?= $website_name ?></a></li>
					<?php endif; ?>
				</ul>
			</div>
			<div class="col-flexible hide-sm text-right">
				<?php if($is_admin): ?>
					<a href="admin/" target="_blank"><span>Admin CP</span><i class="fa fa-lock"></i></a>
				<?php endif; ?>
				<a href="search"><span><?php __("global.search") ?></span><i class="fa fa-search"></i></a>
				<a href="members"><span><?php __("global.memberlist") ?></span><i class="fa fa-users"></i></a>
				<a href="calendar"><span><?php __("global.calendar") ?></span><i class="fa fa-calendar"></i></a>
				<?php if($member_id == 0): ?>
					<a href="register"><span><?php __("global.create_account") ?></span><i class="fa fa-star"></i></a>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<div class="bottom-half outer">
		<div class="row content-between">
			<div class="col-flexible">
				<a href="<?= $community_url ?>">
					<img src="static/images/logo.svg" class="logo" alt="Addictive Community">
				</a>
			</div>
			<div class="col-flexible nav-button show-sm text-right" id="toggle-sidebar">
				<i class="fa fa-bars"></i>
			</div>
			<div class="col-flexible search hide-sm">
				<form action="search" method="get" class="no-validate">
					<input type="search" name="q" class="form-control search-input" value="<?= \AC\Kernel\Http::request("q") ?>" placeholder="<?php __("global.search") ?>..."><!--
					--><button type="submit" class="btn btn-default search-submit">
						<i class="fa fa-search"></i>
					</button>
				</form>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<ul class="breadcrumb">
					<?= $breadcrumb ?>
				</ul>
			</div>
		</div>
	</div>
</header>
