<div class="article">
	<div class="article-header" style="background-image: url('<?= $attachment['url'] ?>')">
		<div class="article-header-shadow"></div>
		<div class="article-header-title"><?= $article['title'] ?></div>
	</div>
	<div class="article-content block">
		<div class="article-content-info">
			<?= __("articles.read.written_by", $article['username']) ?>
			<i class="at fa fa-clock-o"></i> <?= date('d M Y\, H:i', $article['post_date']) ?>
		</div>
		<div class="article-content-container">
			<?= $article['content'] ?>
		</div>
	</div>
	<!-- <div class="article-options block">
		xxxx
	</div> -->
</div>
