<div class="articles-options pull-clear">
	<div class="articles-options-title pull-left"><?php __("articles.latest_articles") ?></div>
	<?php if($is_member): ?>
		<a href="articles/add" class="btn btn-success pull-right"><?php __("articles.add.title") ?></a>
	<?php endif; ?>
</div>
<div class="articles-index">
	<?php foreach($articles as $article): ?>
		<div class="article-item">
			<div class="content">
				<div class="image" style="background-image: url('/public/attachments/<?= $article['member_id'] ?>/<?= $article['date'] ?>/<?= $article['filename'] ?>')"></div>
				<div class="details">
					<a href="./articles/read/<?= $article['a_id'] ?>" class="title"><?= $article['title'] ?></a>
					<span class="author">By <a href=""><?= $article['username'] ?></a> in <?= date('d M Y\, H:i', $article['post_date']) ?></span>
					<p class="excerpt"><?= strip_tags($article['content']) ?></p>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
</div>
