<div class="article">
	<div class="article-header" style="background-image: url(http://placehold.it/640x480)">
		<div class="article-header-shadow"></div>
		<div class="article-header-title"><?= $teste ?></div>
	</div>
	<div class="article-content block">
		<div class="article-content-info">
			Written by Brunno Pleffken <i class="at fa fa-clock-o"></i> 27 July 2017, 00:10
			<div class="pull-right">
				<small>12 Votes:</small>
				<i class="star fa fa-star"></i>
				<i class="star fa fa-star"></i>
				<i class="star fa fa-star"></i>
				<i class="star fa fa-star-half-o"></i>
				<i class="star fa fa-star-o"></i>
			</div>
		</div>
		<div class="article-content-container">
			<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione alias blanditiis aliquam nihil sit, amet voluptatibus provident dolorem, dolores earum dignissimos ipsum facere hic velit repudiandae rem doloribus tenetur, nulla accusamus voluptate ducimus assumenda! Nihil alias, facere doloribus autem consectetur harum libero quis quod? Aperiam ad earum facere odio eos!</p>
			<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sed consectetur amet facere possimus soluta maiores ullam. Voluptates facilis, molestiae quaerat porro corporis eaque cumque perspiciatis odit blanditiis repellat tempora debitis exercitationem unde distinctio beatae sequi ad aperiam provident laudantium autem aliquid explicabo hic? Numquam nobis possimus, vero asperiores tempora fugit, optio enim quaerat minus magni aperiam magnam eos. Suscipit dolores cupiditate qui nihil nesciunt laborum magnam hic saepe iusto quas, atque, impedit ducimus deleniti quasi ipsam fugit. Est cupiditate amet odio molestiae, illo quaerat dolores libero quod, eaque aspernatur quia repellendus ipsam accusamus, corporis sed. Ratione ea debitis quis temporibus!</p>
			<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repellat amet ipsam ex id nesciunt enim placeat nulla perferendis labore molestias, repellendus dolorum suscipit et illum ad nam temporibus, magni possimus consequatur, impedit minus adipisci ratione. Laborum consequuntur ipsa soluta amet?</p>
			<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nemo assumenda alias dignissimos odio voluptatum id, perspiciatis asperiores dolores, cum voluptate numquam error necessitatibus fuga accusantium, reiciendis in officia. Optio sed ipsum eveniet distinctio, repellendus consequuntur impedit accusamus error a aliquam vero explicabo, asperiores rem iusto animi suscipit. Consectetur dolor nam natus illum minima ipsa numquam adipisci mollitia voluptatibus dignissimos, qui officiis laborum molestias veritatis, laudantium repudiandae ab eaque. Voluptate quos accusamus soluta autem, quisquam est adipisci beatae cumque dolores iste ullam expedita repellat pariatur modi libero id facilis repudiandae dignissimos illo porro nisi qui labore sequi. Placeat est, cum debitis inventore accusamus odit omnis qui tempore nihil? Libero minus culpa dolorum quasi consequuntur, cum ut ab, aut, explicabo itaque voluptas!</p>
		</div>
	</div>
	<div class="article-options block">
		xxxx
	</div>
</div>
