<h1>
	<small><?= $community_name ?></small>
	<?php __("calendar.title") ?>
</h1>

<div class="block">
	<form method="get" id="calendar-set-date">
		<?php __("calendar.go_to") ?>:
		<?= \AC\Kernel\Html::months("month", false, $c_month) ?>
		<?= \AC\Kernel\Html::years("year", 2, 2, $c_year) ?>
		<input type="submit" class="btn btn-default" value="<?php __("calendar.go") ?>">
	</form>
</div>

<?= $calendar ?>

<div class="text-right">
	<a href="calendar/add" class="btn btn-default"><?php __("calendar.add") ?></a>
	<a href="calendar" class="btn btn-default"><?php __("calendar.show") ?></a>
</div>
