<div class="title-bar">
	<div class="title">
		<span><?php __($community_name) ?></span>
		<?php __("C_TITLE") ?>: <?php __($formatted_date) ?>
	</div>
</div>

<div class="navigation">
	<div class="navbar">
		<a href="room/" class="selected"><?php __("C_VIEW") ?></a>
	</div>
	<div class="subnav">
		<a href="room/"><?php __("C_VIEW_ALL") ?></a>
	</div>
</div>

<?php if($count || $bday_count): ?>
	<div class="events-container">
	<?php foreach($birthdays as $birthday): ?>
		<div class="calendar-events">
			<div class="marker"><span></span></div>
			<div class="details">
				<div class="box">
					<div class="event-time" style="text-align: center; font-size: 28px;"><i class="fa fa-birthday-cake"></i></div>
					<div class="event-content" style="padding: 15px 0 15px 10px">
						<h3 style="margin:0">Birthday of <a href="profile/<?php __($birthday['m_id']) ?>"><?php __($birthday['username']) ?></a></h3>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	<?php foreach($events as $event): ?>
		<div class="calendar-events">
			<div class="marker"><span></span></div>
			<div class="details">
				<div class="box">
					<div class="event-time"><?php __(date("H:i", $event['timestamp'])) ?></div>
					<div class="event-content">
						<h3><?php __($event['title']) ?></h3>
						<div class="tiny"><?php __("C_VIEW_BY", $event['username']) ?></div>
						<?php __($event['text']) ?>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	</div>
<?php else: ?>
	<div class="box center">
		<?php __("C_NO_EVENTS") ?>
	</div>
<?php endif; ?>
