<h1>
	<small><?php echo $community_name ?></small>
	<?php __("C_TITLE") ?>
</h1>

<div class="block">
	<form method="get" id="calendar-set-date">
		<?php __("C_GOTO") ?>:
		<?php echo \AC\Kernel\Html::Months("month", false, $c_month) ?>
		<?php echo \AC\Kernel\Html::Years("year", 2, 2, $c_year) ?>
		<input type="submit" class="btn btn-default" value="<?php __("C_GO") ?>">
	</form>
</div>

<?php echo $calendar ?>

<div class="text-right">
	<a href="calendar/add" class="btn btn-default"><?php __("C_ADD") ?></a>
	<a href="calendar" class="btn btn-default"><?php __("C_SHOW") ?></a>
</div>
