<h1>
	<small><?= $community_name ?></small>
	<?php __("C_TITLE") ?>: <?= $formatted_date ?>
</h1>

<div class="nav room-nav">
	<div class="nav-top">
		<a href="calendar/view?date=<?= \AC\Kernel\Http::Request("date") ?>" class="active"><?php __("C_VIEW") ?></a>
	</div>
	<div class="nav-bottom">
		<a href="calendar/view?date=<?= \AC\Kernel\Http::Request("date") ?>"><?php __("C_VIEW_ALL") ?></a>
		<a href="calendar/view?date=<?= \AC\Kernel\Http::Request("date") ?>&type=private"><?php __("C_VIEW_PRIVATE") ?></a>
	</div>
</div>

<?php if($events_count || $bday_count): ?>
	<div class="events-container">
	<?php foreach($birthdays as $birthday): ?>
		<div class="calendar-events">
			<div class="marker"><span></span></div>
			<div class="details">
				<div class="block">
					<div class="event-time" style="text-align: center; font-size: 28px;"><i class="fa fa-birthday-cake"></i></div>
					<div class="event-content" style="padding: 15px 0 15px 10px">
						<h3 style="margin:0">Birthday of <a href="profile/<?= $birthday['m_id'] ?>"><?= $birthday['username'] ?></a></h3>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	<?php foreach($events as $event): ?>
		<div class="calendar-events">
			<div class="marker"><span></span></div>
			<div class="details">
				<div class="block">
					<div class="event-time"><?= date("H:i", $event['timestamp']) ?></div>
					<div class="event-content">
						<h3><?= $event['title'] ?></h3>
						<div class="tiny"><?php __("C_VIEW_BY", $event['username']) ?></div>
						<p><?= $event['text'] ?></p>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	</div>
<?php else: ?>
	<div class="block text-center">
		<?php __("C_NO_EVENTS") ?>
	</div>
<?php endif; ?>

<div class="text-right">
	<a href="calendar?month=<?= $date[1] ?>&year=<?= $date[0] ?>" class="btn btn-default"><?php __("C_TITLE") ?></a>
</div>
