<?php foreach($categories as $i => $category): ?>
	<div class="room-category" data-toggle-id="<?php __($i) ?>"><?php __($category['name']) ?><i class="fa fa-angle-down"></i></div>
	<div id="category-<?php __($i) ?>">
		<?php if(isset($rooms[$i])): ?>
			<?php foreach($rooms[$i] as $k => $room): ?>
				<table class="room-item">
					<tr>
						<td class="image"><?php __($room['icon']) ?></td>
						<td class="info">
							<a href="<?php __($room['room_link']) ?>" class="title"><?php __($room['name']) ?></a>
							<p class="description"><?php __($room['description']) ?></p>
							<?php __($room['moderators_list']) ?>
							<?php __($room['redirect']) ?>
							<div class="last-post">
								<span><i class="fa fa-comment"></i>&nbsp; <?php __($room['title']) ?></span>
								<span><i class="fa fa-user"></i>&nbsp; <a href="profile/<?php __($room['lastpost_member']) ?>"><?php __($room['username']) ?></a></span>
								<span><i class="fa fa-clock-o"></i>&nbsp; <?php __($room['lastpost_date']) ?></span>
							</div>
						</td>
						<td class="room-stats">
							<div class="item">
								<i class="fa fa-comments fleft"></i>
								<span class="fright"><?php __($room['thread_count']) ?></span>
							</div>
							<div class="item">
								<i class="fa fa-eye fleft"></i>
								<span class="fright"><?php __($room['online']['total']) ?></span>
							</div>
						</td>
					</tr>
				</table>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
<?php endforeach; ?>

<?php if($is_logged): ?>
	<div class="fright"><a href="community/mark_all_as_read" class="room-mark-as-read"><?php __("C_MARK_ALL_READ") ?></a></div>
<?php endif; ?>
