<?php foreach($categories as $i => $category): ?>
	<div class="category" data-toggle-id="<?= $i ?>">
		<?= $category['name'] ?><i class="fa fa-angle-down"></i>
	</div>

	<div class="category-container" id="category-<?= $i ?>">
		<?php if(isset($rooms[$i])): ?>
			<?php foreach($rooms[$i] as $k => $room): ?>
				<div class="block padding-no community">
					<div class="community-icon text-center">
						<?= $room['icon'] ?>
					</div>
					<div class="community-info">
						<a href="<?= $room['room_link'] ?>" class="community-info-title"><?= $room['name'] ?></a>
						<p class="community-info-description"><?= $room['description'] ?></p>
						<?= $room['moderators_list'] ?>
						<?= $room['redirect'] ?>
						<hr>
						<div class="community-info-stats">
							<span>
								<i class="fa fa-fw fa-comment"></i>
								<?= $room['title'] ?>
							</span>
							<span>
								<i class="fa fa-fw fa-user"></i>
								<a href="profile/<?= $room['last_post_member'] ?>"><?= $room['username'] ?></a>
							</span>
							<span>
								<i class="fa fa-fw fa-clock-o"></i>
								<?= $room['last_post_date'] ?>
							</span>
						</div>
					</div>
					<div class="community-stats">
						<div class="community-stats-item">
							<i class="fa fa-fw fa-comments"></i>
							<span class="pull-right"><?= $room['thread_count'] ?></span>
						</div>
						<div class="community-stats-item">
							<i class="fa fa-fw fa-user"></i>
							<span class="pull-right"><?= $room['online']['total'] ?></span>
						</div>
					</div>
				</div>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
<?php endforeach; ?>

<?php if($is_logged): ?>
	<div class="community-mark-as-read text-right">
		<a href="community/mark_all_as_read"><?php __("community.mark_all_read") ?></a>
	</div>
<?php endif; ?>
