<div class="about">
	<a href="http://github.com/brunnopleffken/addictive-community" target="_blank"><img src="themes/default-light/images/logo.png" height="50" alt="Addictive Community"></a>
	<p class="small"><strong><?php __($community_name) ?></strong> is proudly powered by:</p>
	<div class="box">
		<span class="small">Addictive Community <?php __($data['version']) ?></span><br><br>
		&copy; 2015 - Addictive Community and its licensors. All rights reserved.<br>
		Documentation and source at <a href="http://github.com/brunnopleffken/addictive-community" target="_blank">GitHub</a>. Found a bug? Report it <a href="https://github.com/brunnopleffken/addictive-community/issues" target="_blank">here</a>!
	</div>
</div>
