<h1>
	<small><?= $community_name ?></small>
	<?= $title ?>
</h1>

<?= $error ?>

<?php if($action == "login"): ?>
	<form action="login/authenticate" method="post">
		<div class="block">
			<div class="form-group grid">
				<label class="col-2"><?php __("login.username") ?></label>
				<div class="col-4">
					<input type="text" name="username" class="form-control" required>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("login.password") ?></label>
				<div class="col-4">
					<input type="password" name="password" class="form-control" required>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-left">
					<div class="error-message"><?php __("E_LOGIN_ERROR") ?></div>
				</div>
				<div class="pull-right">
					<input type="submit" value="<?php __("E_LOGIN") ?>" class="btn btn-default">
				</div>
			</div>
		</div>
	</form>
<?php elseif($action == "protected"): ?>
	<form action="room/unlock" method="post">
		<div class="block">
			<div class="form-group grid">
				<label class="col-2"><?php __("failure.password") ?></label>
				<div class="col-4">
					<input type="password" name="password" class="form-control" required>
				</div>
			</div>
			<div class="text-right">
				<input type="hidden" name="room" value="<?= $_GET['room'] ?>">
				<input type="submit" value="<?php __("failure.proceed") ?>" class="btn btn-default">
			</div>
		</div>
	</form>
<?php elseif($action == "offline"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-user-times" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.offline.title") ?></h2><br>
		<h3><?php __("failure.offline.message", $community_name) ?></h3>
	</div>
<?php elseif($action == "update"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-refresh fa-spin" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.updating.title") ?></h2><br>
		<h3><?php __("failure.updating.message") ?></h3>
	</div>
<?php elseif($action == "deleted"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-user-times" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.deleted.title") ?></h2><br>
		<h3><?php __("failure.deleted.message") ?></h3>
	</div>
<?php elseif($action == "banned"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-ban" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.banned.title") ?></h2><br>
		<h3><?php __("failure.banned.message") ?></h3>
	</div>
<?php elseif($action == "403"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-hand-paper-o" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.forbidden.title") ?></h2><br>
		<h3><?php __("failure.forbidden.message") ?></h3>
	</div>
<?php elseif($action == "404"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-meh-o" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.not_found.title") ?></h2><br>
		<h3><?php __("failure.not_found.message") ?></h3>
	</div>
<?php elseif($action == "500"): ?>
	<div class="block text-center" style='padding: 40px 0'>
		<i class="fa fa-exclamation-triangle" style="font-size: 56px"></i><br><br>
		<h2><?php __("failure.server_error.title") ?></h2><br>
		<h3><p><?php __("failure.server_error.message") ?></p></h3>
	</div>
<?php endif; ?>
