<div class="title-bar">
	<div class="title fleft">
		<span><?php __($community_name) ?></span><?php __($title) ?>
	</div>
</div>

<?php __($error) ?>

<?php if($action == "login"): ?>
	<form action="login/authenticate" method="post" class="validate">
		<div class="box">
			<div class="input-box">
				<div class="label"><?php __("E_USERNAME") ?></div>
				<div class="field"><input type="text" name="username" class="required medium"></div>
			</div>
			<div class="input-box">
				<div class="label"><?php __("E_PASSWORD") ?></div>
				<div class="field"><input type="password" name="password" class="required medium"></div>
			</div>
			<div class="fleft">
				<div class="error-message"><?php __("E_LOGIN_ERROR") ?></div>
			</div>
			<div class="fright">
				<input type="hidden" name="exception_referrer" value="true">
				<input type="submit" value="<?php __("E_LOGIN") ?>">
			</div>
		</div>
	</form>
<?php elseif($action == "protected"): ?>
	<form action="room/unlock" method="post" class="validate">
		<div class="box">
			<div class="input-box">
				<div class="label"><?php __("E_PASSWORD") ?></div>
				<div class="field"><input type="password" name="password" class="required medium"></div>
			</div>
			<div class="fright">
				<input type="hidden" name="room" value="<?php echo $_GET['room'] ?>">
				<input type="submit" value="<?php __("E_PROCEED") ?>">
			</div>
		</div>
	</form>
<?php elseif($action == "offline"): ?>
	<div class="box center" style='padding: 40px 0'>
		<i class="fa fa-user-times" style="font-size: 50px"></i><br><br>
		<h2><?php __("E_OFFLINE_TITLE") ?></h2><br>
		<h3><?php __("E_OFFLINE_MESSAGE", $community_name) ?></h3>
	</div>
<?php elseif($action == "update"): ?>
	<div class="box center" style='padding: 40px 0'>
		<i class="fa fa-refresh" style="font-size: 50px"></i><br><br>
		<h2><?php __("E_UPDATING") ?></h2><br>
		<h3><?php __("E_UPDATING_MESSAGE", $community_name) ?></h3>
	</div>
<?php elseif($action == "deleted"): ?>
	<div class="box center" style='padding: 40px 0'>
		<i class="fa fa-user-times" style="font-size: 50px"></i><br><br>
		<h2><?php __("E_DELETED") ?></h2><br>
		<h3><?php __("E_DELETED_MESSAGE", $community_name) ?></h3>
	</div>
<?php endif; ?>
