<div class="header">
	<h1>
		<small><?= $community_name ?></small>
		<?php __("messenger.title") ?>
	</h1>
	<div class="header-buttons">
		<a href="messenger/compose" class="btn btn-default"><?php __("messenger.new_message") ?></a>
	</div>
</div>

<?= $notification ?>

<div class="nav room-nav">
	<div class="nav-top">
		<a href="messenger" class="active"><?php __("messenger.folders") ?></a>
	</div>
	<div class="nav-bottom">
		<a href="messenger"><?php __("messenger.inbox") ?></a>
		<a href="messenger?folder=sent"><?php __("messenger.sent") ?></a>
		<?php if(\AC\Kernel\Http::request("folder") != "sent"): ?>
			<div class="progress-bar" style="width: 200px; float: right; margin-top: 8px">
				<div class="fill" style="width: <?= $percentage_width ?>"></div>
				<span><?php __("messenger.storage", array($num_results, $max_storage_size)) ?></span>
			</div>
		<?php endif; ?>
	</div>
</div>

<div class="block padding-no">
	<?php if($folder == "inbox"): ?>
		<form action="messenger/delete" method="post" class="personal-messenger">
			<table class="table">
				<thead>
					<tr>
						<th colspan="5">
							<?php __("messenger.inbox") ?>
							<div class="pull-right text-s0">
								<a class="label invert" id="delete-messages"><?php __("messenger.delete_selected") ?></a>
							</div>
						</th>
					</tr>
					<tr>
						<td class="min"></td>
						<td><?php __("messenger.subject") ?></td>
						<td width="20%"><?php __("messenger.from") ?></td>
						<td width="22%"><?php __("messenger.date") ?></td>
						<td class="min text-center"><i class="fa fa-check-square-o"></i></td>
					</tr>
				</thead>
				<tbody>
					<?php if($num_results): ?>
						<?php foreach($results as $pm): ?>
							<tr>
								<td><i class="fa fa-fw <?= $pm['icon_class'] ?>"></i></td>
								<td><a href="messenger/read/<?= $pm['pm_id'] ?>"><?= $pm['subject'] ?></a></td>
								<td><a href="profile/<?= $pm['from_id'] ?>"><?= $pm['username'] ?></a></td>
								<td><?= $pm['sent_date'] ?></td>
								<td class="text-center">
									<label class="checkbox-control padding-no">
										<input type="checkbox" name="pm[]" value="<?= $pm['pm_id'] ?>" class="del-message-checkbox">
										<span><i class="fa fa-check"></i></span>
									</label>
								</td>
							</tr>
						<?php endforeach; ?>
					<?php else: ?>
						<tr>
							<td colspan="5" class="text-center"><?php __("messenger.no_pm_inbox") ?></td>
						</tr>
					<?php endif; ?>
				</tbody>
			</table>
		</form>
	<?php else: ?>
		<table class="table">
			<thead>
				<tr>
					<th colspan="5">
						<?php __("messenger.sent") ?>
					</th>
				</tr>
				<tr>
					<td><?php __("messenger.subject") ?></td>
					<td width="20%"><?php __("messenger.to") ?></td>
					<td width="22%"><?php __("messenger.date") ?></td>
				</tr>
			</thead>
			<tbody>
				<?php if($num_results): ?>
					<?php foreach($results as $pm): ?>
						<tr>
							<td><a href="messenger/read/<?= $pm['pm_id'] ?>"><?= $pm['subject'] ?></a></td>
							<td><a href="profile/<?= $pm['to_id'] ?>"><?= $pm['username'] ?></a></td>
							<td><?= $pm['sent_date'] ?></td>
						</tr>
					<?php endforeach; ?>
					<?php else: ?>
					<tr>
						<td colspan="5" class="text-center"><?php __("messenger.no_pm_sent") ?></td>
					</tr>
				<?php endif; ?>
			</tbody>
		</table>
	<?php endif; ?>
</div>
