<div class="header">
	<?php if($message['to_id'] == $member_id): ?>
		<h1>
			<small><?php echo $community_name ?></small>
			<?php echo $message['subject'] ?>
		</h1>
		<div class="header-buttons">
			<a href="messenger/reply/<?php echo $message['pm_id'] ?>" class="btn btn-default"><?php __("M_REPLY") ?></a>
			<a href="messenger/forward/<?php echo $message['pm_id'] ?>" class="btn btn-default"><?php __("M_FORWARD") ?></a>
			<a href="messenger/delete/<?php echo $message['pm_id'] ?>" class="btn btn-default"><?php __("M_DELETE") ?></a>
		</div>
	<?php else: ?>
		<h1>
			<small><?php echo $community_name ?></small>
			<?php __("M_FOLDER_SENT") ?>: <?php echo $message['subject'] ?>
		</h1>
	<?php endif; ?>
</div>

<div class="block padding-no thread-reply">
	<div class="thread-reply-content">
		<div class="thread-reply-content-author text-center">
			<div class="thread-reply-content-author-avatar">
				<?php echo \AC\Kernel\Html::Crop($message['avatar'], 98, "image") ?>
			</div>
			<a href="profile/<?php echo $message['from_id'] ?>" class="thread-reply-content-author-username">
				<?php echo $message['username'] ?>
			</a>
		</div>
		<div class="thread-reply-content-body">
			<div class="thread-reply-content-body-date">
				<?php __("M_SENT_ON", array($message['sent_date'])) ?>
			</div>
			<div class="thread-reply-content-body-post">
				<?php echo $message['message'] ?>
			</div>
		</div>
	</div>
</div>
