<div class="header">
	<?php if($message['to_id'] == $member_id): ?>
		<h1>
			<small><?= $community_name ?></small>
			<?= $message['subject'] ?>
		</h1>
		<div class="header-buttons">
			<a href="messenger/reply/<?= $message['pm_id'] ?>" class="btn btn-default"><?php __("M_REPLY") ?></a>
			<a href="messenger/forward/<?= $message['pm_id'] ?>" class="btn btn-default"><?php __("M_FORWARD") ?></a>
			<a href="messenger/delete/<?= $message['pm_id'] ?>" class="btn btn-default"><?php __("M_DELETE") ?></a>
		</div>
	<?php else: ?>
		<h1>
			<small><?= $community_name ?></small>
			<?php __("M_FOLDER_SENT") ?>: <?= $message['subject'] ?>
		</h1>
	<?php endif; ?>
</div>

<div class="block padding-no thread-reply">
	<div class="thread-reply-content">
		<div class="thread-reply-content-author text-center">
			<div class="thread-reply-content-author-avatar">
				<?= \AC\Kernel\Html::Crop($message['avatar'], 98, "image") ?>
			</div>
			<a href="profile/<?= $message['from_id'] ?>" class="thread-reply-content-author-username">
				<?= $message['username'] ?>
			</a>
		</div>
		<div class="thread-reply-content-body">
			<div class="thread-reply-content-body-date">
				<?php __("M_SENT_ON", array($message['sent_date'])) ?>
			</div>
			<div class="thread-reply-content-body-post">
				<?= $message['message'] ?>
			</div>
		</div>
	</div>
</div>
