<h1>
	<small><?= $community_name ?></small>
	<?php __("M_TITLE") ?>: <?php __("M_REPLY") ?>
</h1>

<div class="block">
	<form action="messenger/send" method="post">
		<div class="form-group grid">
			<label class="col-2"><?php __("M_TO") ?></label>
			<div class="col-4">
				<input type="hidden" name="to" value="<?= $message['reply_user_id'] ?>">
				<div class="form-control-static"><?= $message['username'] ?></div>
			</div>
		</div>
		<div class="form-group grid">
			<label class="col-2"><?php __("M_SUBJECT") ?></label>
			<div class="col-6">
				<input type="text" name="subject" class="form-control" value="Re: <?= $message['subject'] ?>" required>
			</div>
		</div>
		<div class="form-group grid">
			<label for="" class="col-2"><?php __("M_MESSAGE") ?></label>
			<div class="col-10">
				<textarea name="post" id="post" rows="20"></textarea>
			</div>
		</div>
		<div class="pull-clear">
			<div class="pull-left">
				<div class="error-message"><?php __("M_PM_ERROR") ?></div>
			</div>
			<div class="pull-right">
				<input type="submit" class="btn btn-default" value="<?php __("M_SEND") ?>">
			</div>
		</div>
	</form>
</div>
