<div class="profile-header">
	<div class="profile-header-background" style="background-image: url('<?= $info['cover'] ?>')">
		<div class="inner-shadow"></div>
	</div>
	<div class="profile-header-info">
		<div class="avatar">
			<a href="<?= $info['avatar'] ?>" class="fancybox fancybox.image">
				<?= \AC\Kernel\Html::crop($info['avatar'], 150, "image") ?>
			</a>
		</div>
		<div class="details">
			<div class="username"><?= $info['username'] ?></div>
			<div class="item"><span><?php __("profile.posts") ?></span><?= $info['posts'] ?></div>
			<div class="item"><span><?php __("profile.registered") ?></span><?= $info['joined'] ?></div>
			<div class="item"><span><?php __("profile.usergroup") ?></span><?= $info['name'] ?></div>
		</div>
	</div>
</div>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="profile/<?= $profile_member_id ?>" class="active"><?php __("profile.title") ?></a>
			<a href="profile/posts/<?= $profile_member_id ?>"><?php __("profile.last_posts") ?></a>
			<a href="profile/attachments/<?= $profile_member_id ?>"><?php __("profile.attachments") ?></a>
		</div>
	</div>
	<div class="block-nav-content">
		<table class="table vertical-aligned no-border">
			<thead>
				<tr>
					<td colspan="2" class="text-s14"><?php __("profile.my_profile") ?></td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="min text-muted text-right"><?php __("profile.about_me") ?></td>
					<td><p><?= nl2br($info['profile']) ?></p></td>
				</tr>
				<tr>
					<td class="min text-muted text-right"><?php __("profile.birthdate") ?></td>
					<td><?php if($has_birthday) __("profile.age", array($info['birthday'], $info['age'])) ?></td>
				</tr>
				<tr>
					<td class="min text-muted text-right"><?php __("profile.gender") ?></td>
					<td><?= $info['gender'] ?></td>
				</tr>
				<tr>
					<td class="min text-muted text-right"><?php __("profile.location") ?></td>
					<td><?= $info['location'] ?></td>
				</tr>
				<tr>
					<td class="min text-muted text-right"><?php __("profile.website") ?></td>
					<td><?= $info['website'] ?></td>
				</tr>
				<tr>
					<td class="min text-muted text-right"><?php __("profile.signature") ?></td>
					<td><?= $info['signature'] ?></td>
				</tr>
			</tbody>
		</table>
		<table class="table vertical-aligned no-border">
			<thead>
				<tr>
					<td colspan="2" class="text-s14"><?php __("profile.stats") ?></td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="min text-muted"><?php __("profile.best_answers") ?></td>
					<td><?php __("profile.best_posts", array($info['bestanswers'])) ?></td>
				</tr>
			</tbody>
		</table>
		<table class="table vertical-aligned no-border">
			<thead>
				<tr>
					<td colspan="2" class="text-s14"><?php __("profile.contact") ?></td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="min"><i class="fa fa-fw fa-envelope-o"></i></td>
					<td><?= $info['email'] ?></td>
				</tr>
				<?php if($info['im_facebook']): ?>
					<tr>
						<td class="min"><i class="fa fa-fw fa-facebook-square"></i></td>
						<td><a href="https://www.facebook.com/<?= $info['im_facebook'] ?>" target="_blank" rel="nofollow">fb.me/<?= $info['im_facebook'] ?></a></td>
					</tr>
				<?php endif; ?>
				<?php if($info['im_twitter']): ?>
					<tr>
						<td class="min"><i class="fa fa-fw fa-twitter"></i></td>
						<td><a href="https://twitter.com/<?= $info['im_twitter'] ?>" target="_blank" rel="nofollow">@<?= $info['im_twitter'] ?></a></td>
					</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
