<div class="profile-header">
	<div class="profile-header-background" style="background-image: url('<?= $info['cover'] ?>')">
		<div class="inner-shadow"></div>
	</div>
	<div class="profile-header-info">
		<div class="avatar">
			<a href="<?= $info['avatar'] ?>" class="fancybox fancybox.image">
				<?= \AC\Kernel\Html::crop($info['avatar'], 150, "image") ?>
			</a>
		</div>
		<div class="details">
			<div class="username"><?= $info['username'] ?></div>
			<div class="item"><span><?php __("profile.posts") ?></span><?= $info['posts'] ?></div>
			<div class="item"><span><?php __("profile.registered") ?></span><?= $info['joined'] ?></div>
			<div class="item"><span><?php __("profile.usergroup") ?></span><?= $info['name'] ?></div>
		</div>
	</div>
</div>


<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="profile/<?= $profile_member_id ?>"><?php __("profile.title") ?></a>
			<a href="profile/posts/<?= $profile_member_id ?>" class="active"><?php __("profile.last_posts") ?></a>
			<a href="profile/attachments/<?= $profile_member_id ?>"><?php __("profile.attachments") ?></a>
		</div>
	</div>
	<div class="block-nav-content">
		<table class="table">
			<thead>
				<tr>
					<td class="text-s14" colspan="2"><?php __("profile.last_threads_by", array($info['username'])) ?></td>
				</tr>
			</thead>
			<tbody>
				<?= $thread_list ?>
			</tbody>
		</table>
		<table class="table no-border">
			<thead>
				<tr>
					<td class="text-s14" colspan="2"><?php __("profile.last_posts_by", array($info['username'])) ?></td>
				</tr>
			</thead>
			<tbody>
				<?= $post_list ?>
			</tbody>
		</table>
	</div>
</div>
