<div class="profile-header">
	<div class="profile-header-background" style="background-image: url('<?= $info['cover'] ?>')">
		<div class="inner-shadow"></div>
	</div>
	<div class="profile-header-info">
		<div class="avatar">
			<a href="<?= $info['avatar'] ?>" class="fancybox fancybox.image">
				<?= \AC\Kernel\Html::crop($info['avatar'], 150, "image") ?>
			</a>
		</div>
		<div class="details">
			<div class="username"><?= $info['username'] ?></div>
			<div class="item"><span><?php __("profile.posts") ?></span><?= $info['posts'] ?></div>
			<div class="item"><span><?php __("profile.registered") ?></span><?= $info['joined'] ?></div>
			<div class="item"><span><?php __("profile.usergroup") ?></span><?= $info['name'] ?></div>
		</div>
	</div>
</div>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="profile/<?= $profile_member_id ?>"><?php __("profile.title") ?></a>
			<a href="profile/posts/<?= $profile_member_id ?>"><?php __("profile.last_posts") ?></a>
			<a href="profile/attachments/<?= $profile_member_id ?>" class="active"><?php __("profile.attachments") ?></a>
		</div>
	</div>
	<div class="block-nav-content">
		<table class="table">
			<thead>
				<tr>
					<td></td>
					<td class="text-s14"><?php __("profile.file_name") ?></td>
					<td class="text-s14"><?php __("profile.file_type") ?></td>
					<td class="text-s14"><?php __("profile.file_size") ?></td>
				</tr>
			</thead>
			<tbody>
				<?php if(!empty($attachments)): ?>
					<?php foreach($attachments as $file): ?>
						<tr>
							<td class="min"><?= $file['icon'] ?></td>
							<td><?= $file['filename'] ?></td>
							<td><?= $file['type'] ?></td>
							<td><?= $file['size'] ?></td>
						</tr>
					<?php endforeach; ?>
				<?php else: ?>
					<tr>
						<td colspan="4" class="text-center"><?php __("profile.no_attachments") ?></td>
					</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
