<div class="profile-header">
	<div class="profile-header-background" style="background-image: url('<?php echo $info['cover'] ?>')">
		<div class="inner-shadow"></div>
	</div>
	<div class="profile-header-info">
		<div class="avatar">
			<a href="<?php echo $info['avatar'] ?>" class="fancybox fancybox.image">
				<?php __(\AC\Kernel\Html::Crop($info['avatar'], 150, "image")) ?>
			</a>
		</div>
		<div class="details">
			<div class="username"><?php echo $info['username'] ?></div>
			<div class="item"><span><?php __("P_POSTS") ?></span><?php echo $info['posts'] ?></div>
			<div class="item"><span><?php __("P_REGISTERED") ?></span><?php echo $info['joined'] ?></div>
			<div class="item"><span><?php __("P_USERGROUP") ?></span><?php echo $info['name'] ?></div>
		</div>
	</div>
</div>


<div class="block no-padding">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="profile/<?php echo $profile_member_id ?>"><?php __("P_PROFILE") ?></a>
			<a href="profile/posts/<?php echo $profile_member_id ?>" class="active"><?php __("P_LAST_POSTS") ?></a>
			<a href="profile/attachments/<?php echo $profile_member_id ?>"><?php __("P_ATTACHMENTS") ?></a>
		</div>
	</div>
	<div class="block-nav-content">
		<table class="table">
			<thead>
				<tr>
					<td class="text-s14" colspan="2"><?php __("P_LAST_THREADS_BY", array($info['username'])) ?></td>
				</tr>
			</thead>
			<tbody>
				<?php echo $thread_list ?>
			</tbody>
		</table>
		<table class="table no-border">
			<thead>
				<tr>
					<td class="text-s14" colspan="2"><?php __("P_LAST_POSTS_BY", array($info['username'])) ?></td>
				</tr>
			</thead>
			<tbody>
				<?php echo $post_list ?>
			</tbody>
		</table>
	</div>
</div>
