<h1>
	<small><?= $community_name ?></small>
	<?php __("register.title") ?>
</h1>

<?php if($is_register_disabled == 1): ?>
	<?= \AC\Kernel\Html::notification("Registration has been disabled.", "warning", true); ?>
<?php else: ?>
	<div class="block">
		<?php if($step == 1): ?>
			<div class="step-box" style="width: 50%">
				<div class="current"><h3><?php __("register.step1") ?></h3><small><?php __("register.agreement") ?></small></div>
				<div><h3><?php __("register.step2") ?></h3><small><?php __("register.your_account") ?></small></div>
				<div><h3><?php __("register.step3") ?></h3><small><?php __("register.confirmation") ?></small></div>
			</div>
			<div class="form-group text-center">
				<textarea class="form-control" style="max-width: 600px; height: 200px" readonly><?php __("register.eula") ?></textarea>
			</div>
			<div class="form-group text-center margin-no">
				<button class="btn btn-cancel" onclick="javascript:location.href='/'">
					<?php __("register.disagree") ?>
				</button>
				<button class="btn btn-default" onclick="javascript:location.href='register?step=2'">
					<?php __("register.agree") ?>
				</button>
			</div>
		<?php elseif($step == 2): ?>
			<div class="step-box" style="width: 50%">
				<div class="prev"><h3><?php __("register.step1") ?></h3><small><?php __("register.agreement") ?></small></div>
				<div class="current"><h3><?php __("register.step2") ?></h3><small><?php __("register.your_account") ?></small></div>
				<div><h3><?php __("register.step3") ?></h3><small><?php __("register.confirmation") ?></small></div>
			</div>
			<?= $notification ?>
			<form action="register/sign_up" method="post">
				<div class="form-group grid">
					<label class="col-3"><?php __("register.username") ?></label>
					<div class="col-3">
						<input type="text" name="username" id="username" maxlength="20" class="form-control" onkeyup="register.checkUsername()" required>
					</div>
					<em class="form-control-static col-6"><?php __("register.username_notice") ?></em>
				</div>
				<div class="form-group grid">
					<label class="col-3"><?php __("register.password") ?></label>
					<div class="col-3">
						<input type="password" name="password" id="password" class="form-control" required>
					</div>
					<em class="form-control-static col-6"><?php __("register.password_notice") ?></em>
				</div>
				<div class="form-group grid">
					<label class="col-3"><?php __("register.password_retype") ?></label>
					<div class="col-3">
						<input type="password" name="password_conf" id="password_conf" class="form-control" onkeyup="register.checkPassword()" required>
					</div>
					<div id="passwdMatch" class="form-control-static col-6" style="display:none; color:#bb0000; font-weight:bold;">
						<i class="fa fa-exclamation-triangle"></i> <?php __("register.password_error") ?>
					</div>
				</div>
				<div class="form-group grid">
					<label class="col-3"><?php __("register.email") ?></label>
					<div class="col-5">
						<input type="email" name="email" class="form-control" required>
					</div>
				</div>
				<?php if($is_captcha): ?>
					<div class="form-group grid">
						<label class="col-3">
							<?php __("register.captcha") ?>
							<small><?php __("register.captcha_description") ?></small>
						</label>
						<div class="col-9">
							<input type="text" name="captcha" class="form-control span-2" maxlength="6" required>
							<img src="register/captcha" alt="CAPTCHA" style="display: block; margin-top: 10px;">
						</div>
					</div>
				<?php endif; ?>
				<div class="text-right margin-no">
					<input type="submit" id="formSubmit" class="btn btn-default" value="<?php __("register.create") ?>" disabled>
				</div>
			</form>
		<?php elseif($step == 3): ?>
			<div class="step-box" style="width: 50%">
				<div class="prev"><h3><?php __("register.step1") ?></h3><small><?php __("register.agreement") ?></small></div>
				<div class="prev"><h3><?php __("register.step2") ?></h3><small><?php __("register.your_account") ?></small></div>
				<div class="current"><h3><?php __("register.step3") ?></h3><small><?php __("register.confirmation") ?></small></div>
			</div>
			<div class="form-group text-center margin-no">
				<i class="fa fa-check" style="font-size: 50px"></i><br><br>
				<h2><?php __("register.done.congratulations") ?></h2><br>
				<h3><?php __("register.done.success") ?></h3>
				<?php if($general_security_validation): ?>
					<h3><?php __("register.done.validate") ?></h3>
				<?php endif; ?>
			</div>
		<?php elseif($step == 4): ?>
			<div class="step-box" style="width: 50%">
				<div class="prev"><h3><?php __("register.step1") ?></h3><small><?php __("register.agreement") ?></small></div>
				<div class="prev"><h3><?php __("register.step2") ?></h3><small><?php __("register.your_account") ?></small></div>
				<div class="prev"><h3><?php __("register.step3") ?></h3><small><?php __("register.confirmation") ?></small></div>
				<div class="current"><h3><?php __("register.step4") ?></h3><small><?php __("register.validation") ?></small></div>
			</div>
			<div class="form-group text-center margin-no">
				<i class="fa fa-check" style="font-size: 50px"></i><br><br>
				<h2><?php __("register.done.congratulations") ?></h2><br>
				<h3><?php __("register.done.validated") ?></h3>
			</div>
		<?php endif; ?>
	</div>
<?php endif; ?>
