<form action="report/save" method="post" class="validate">
	<table class="table no-border" style="width:390px; margin:0">
		<thead>
			<tr>
				<th>
					<?php __("report.title") ?>
					<div class="pull-right text-s0">
						<a href="javascript:$.fancybox.close();" class="label invert"><?php __("report.close") ?></a>
					</div>
				</th>
			</tr>
		</thead>
		<tr>
			<td>
				<p><?php __("report.notice") ?></p>
			</td>
		</tr>
		<tr>
			<td>
				<span class="form-control-static"><?php __("report.reason") ?>:</span>
				<select name="reason" id="reason" class="select2-no-search span-9">
					<option value="1"><?php __("report.option_1") ?></option>
					<option value="2"><?php __("report.option_2") ?></option>
					<option value="3"><?php __("report.option_3") ?></option>
					<option value="4"><?php __("report.option_4") ?></option>
					<option value="5"><?php __("report.option_5") ?></option>
					<option value="6"><?php __("report.option_6") ?></option>
					<option value="7"><?php __("report.option_7") ?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td><textarea name="description" class="form-control" rows="6" required></textarea></td>
		</tr>
		<tr class="footer">
			<td colspan="2" style="text-align:center; padding:10px">
				<input type="hidden" name="member_id" value="<?= $member_id ?>">
				<input type="hidden" name="thread_id" value="<?= $thread_id ?>">
				<input type="submit" class="btn btn-default" value="<?php __("report.send") ?>">
			</td>
		</tr>
	</table>
</form>
