<div id="fb-root"></div>
<script>(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!-- NOTIFICATIONS -->
<?php __($notification) ?>
<?php __($has_date_notification) ?>

<!-- FIRST POST -->

<div class="thread-first-post">
	<!-- POST HEADER -->
	<div class="header">
		<div class="author">
			<a href="profile/<?php __($first_post_info['author_id']) ?>">
				<?php __(\AC\Kernel\Html::Crop($first_post_info['avatar'], 42, 42, "avatar")) ?>
			</a>
			<div class="author-info">
				<a href="profile/<?php __($first_post_info['author_id']) ?>"><?php __($first_post_info['username']) ?></a>
				<div><?php __($first_post_info['member_title']) ?></div>
				<div><?php __($first_post_info['posts']) ?> <?php __("T_POSTS_LOWCASE") ?></div>
			</div>
			<div class="fright" style="margin-top: 11px">
				<div class="fb-share-button" data-href="<?php echo \AC\Kernel\Http::CurrentUrl() ?>" data-layout="button_count"></div>
			</div>
			<div class="fright" style="margin-top: 11px; margin-right: 10px">
				<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
			</div>
		</div>
	</div>

	<!-- POST CONTENT -->
	<div class="middle">
		<p class="title"><?php __($first_post_info['title']) ?></p>
		<div class="text">
			<div><?php __($first_post_info['post']) ?></div>
			<div class="attachments">
				<?php if($first_post_info['attach_id'] != 0): ?>
					<div class="file">
						<a href="<?php __($first_post_info['attachment_link']) ?>" target="_blank" rel="nofollow">
							<span class="file-icon <?php __($first_post_info['type']) ?>"></span>
							<div class="file-name">
								<span><?php __($first_post_info['filename']) ?></span>
								<?php __(\AC\Kernel\Text::FileSizeFormat($first_post_info['size'])) ?>
							</div>
						</a>
					</div>
				<?php endif; ?>
			</div>
			<?php if($first_post_info['signature'] && $enable_signature): ?>
				<div class="signature"><?php __($first_post_info['signature']) ?></div>
			<?php endif; ?>
		</div>
	</div>

	<!-- POLL -->
	<?php if($thread_info['poll']['has_poll']): ?>
		<div class="poll">
			<p class="title"><?php __($thread_info['poll']['question']) ?></p>
			<?php if($thread_info['poll']['has_voted']): ?>
				<div class="already-voted">
					<i class="fa fa-fw fa-check"></i>
					<span>Already voted</span>
				</div>
				<div class="replies">
					<?php foreach($thread_info['poll']['choices'] as $k => $question): ?>
						<span class="question"><?php __($question) ?></span>
						<div class="progress-bar-container">
							<div class="progress-bar">
								<div class="fill" style="width: <?php echo $thread_info['poll']['replies_p'][$k] ?>%"></div>
								<span><?php echo $thread_info['poll']['replies_n'][$k] ?> votes</span>
							</div>
							<span class="label"><?php echo round($thread_info['poll']['replies_p'][$k], 1) ?>%</span>
						</div>
					<?php endforeach; ?>
				</div>
			<?php else: ?>
				<div class="questions">
					<form action="thread/save_poll/<?php __($thread_id) ?>" method="post" id="poll">
						<?php foreach($thread_info['poll']['choices'] as $index => $question): ?>
							<span class="question">
								<?php if($thread_info['poll']['multiple']): ?>
									<input type="checkbox" name="chosen_option[]" value="<?php echo $index ?>">
								<?php else: ?>
									<input type="radio" name="chosen_option" value="<?php echo $index ?>">
								<?php endif; ?>
								<?php __($question) ?>
							</span>
						<?php endforeach; ?>
						<?php if($this->Session->member_info['m_id'] != 0): ?>
							<input type="submit" value="Vote">
						<?php else: ?>
							<input type="submit" value="You're unable to vote" disabled>
						<?php endif; ?>
					</form>
				</div>
			<?php endif; ?>
		</div>
	<?php endif; ?>

	<!-- POST FOOTER -->
	<div class="footer">
		<p class="fleft">
			<i class="fa fa-clock-o"></i>
			<?php __("T_POSTED_ON", array($first_post_info['post_date'])) ?> <?php __($first_post_info['edited']) ?>
		</p>
		<?php if($this->Session->member_info['m_id'] != 0): ?>
			<div class="fright">
				<?php if($first_post_info['is_author']): ?>
					<div class="closure">
						<a href="thread/edit/<?php __($first_post_info['p_id']) ?>"><i class="fa fa-pencil"></i> <?php __("T_EDIT") ?></a>
					</div>
				<?php endif; ?>
				<div class="closure">
					<a href="report/thread/<?php __($thread_id) ?>" class="fancybox fancybox.ajax">
						<i class="fa fa-warning"></i>
						<?php __("T_REPORT_ABUSE") ?>
					</a>
				</div>
			</div>
		<?php endif; ?>
	</div>
</div>

<!-- NUMBER OF REPLIES / ADD REPLY BUTTON -->

<div class="thread-buttons">
	<p class="replies fleft"><?php __("T_REPLIES") ?>: <span><?php __($thread_info['post_count_display']) ?></span></p>
	<div class="fright">
		<?php if($this->Session->IsMember()): ?>
			<?php if($thread_info['obsolete']): ?>
				<a href="javascript:void()" class="default-button disabled"><?php __("T_BTN_OBSOLETE") ?></a>
			<?php elseif($thread_info['locked'] == 0 && $thread_info['allow_to_reply']): ?>
				<a href="thread/reply/<?php __($thread_id) ?>" class="default-button"><?php __("T_BTN_ADD") ?></a>
			<?php else: ?>
				<a href="javascript:void()" class="default-button disabled"><?php __("T_BTN_LOCKED") ?></a>
			<?php endif; ?>
		<?php endif; ?>
	</div>
</div>

<!-- REPLIES -->

<?php if(!empty($reply)): ?>
	<?php foreach($reply as $k => $v): ?>
		<a id="post-<?php __($reply[$k]['p_id']) ?>"></a>
		<div class="thread-post-reply <?php __($reply[$k]['bestanswer_class']) ?>">
			<!-- REPLY SIDEBAR -->
			<div class="author">
				<?php if($reply[$k]['usergroup'] != 0): ?>
					<div class="photostack">
						<a href="profile/<?php __($reply[$k]['author_id']) ?>">
							<?php __(\AC\Kernel\Html::Crop($reply[$k]['avatar'], 96, 96, "avatar")) ?>
						</a>
					</div>
					<p class="name"><a href="profile/<?php __($reply[$k]['author_id']) ?>"><?php __($reply[$k]['username']) ?></a></p>
					<p class="member-title"><?php __($reply[$k]['member_title']) ?></p>
					<?php if(!empty($reply[$k]['rank'])): ?>
						<div class="rank">
							<div class="rank-pips"><?php __($reply[$k]['rank_pips']); ?></div>
							<span class="rank-name"><?php __($reply[$k]['rank_name']); ?></span>
						</div>
					<?php endif; ?>
					<ul class="user-info">
						<li><b><?php __("T_POST_POSTS") ?></b> <?php __($reply[$k]['posts']) ?> <?php __("T_POSTS_LOWCASE") ?></li>
						<li><b><?php __("T_POST_REGISTERED") ?></b> <?php __($reply[$k]['joined']) ?></li>
						<li><b><?php __("T_POST_LOCATION") ?></b> <?php __($reply[$k]['location']) ?></li>
					</ul>
				<?php else: ?>
					<p class="name deleted"><?php __($reply[$k]['username']) ?></p>
					<p class="member-title">Deleted</p>
				<?php endif; ?>
			</div>

			<!-- REPLY CONTENT -->
			<div class="content">
				<div class="quote">
					<span><?php __("T_REPLY_POST") ?></span>
					<a href="thread/reply/<?php __($thread_id) ?>?quote=<?php __($reply[$k]['p_id']) ?>"><i class="fa fa-fw fa-quote-right"></i></a>
				</div>
				<div class="date"><?php __("T_POSTED_ON", array($reply[$k]['post_date'])) ?> <?php __($reply[$k]['edited']) ?></div>
				<div class="text">
					<?php if($reply[$k]['has_quote']): ?>
						<div class="quote-box">
							<div class="quote-author">
								<?php __("T_QUOTED_POSTED_ON", array($reply[$k]['quote_author'], $reply[$k]['quote_time'])) ?>
							</div>
							<div class="quote-content"><?php echo $reply[$k]['quote_post'] ?></div>
						</div>
					<?php endif; ?>
					<div><?php __($reply[$k]['post']) ?></div>
					<div class="attachments">
						<?php if($reply[$k]['attach_id'] != 0): ?>
							<span class="title">Attachment</span>
							<div class="file">
								<a href="<?php __($reply[$k]['attachment_link']) ?>" target="_blank" rel="nofollow">
									<span class="file-icon <?php __($reply[$k]['type']) ?>"></span>
									<div class="file-name">
										<span><?php __($reply[$k]['filename']) ?></span>
										<?php __(\AC\Kernel\Text::FileSizeFormat($reply[$k]['size'])) ?>
									</div>
								</a>
							</div>
						<?php endif; ?>
					</div>
					<?php if($reply[$k]['signature'] && $enable_signature): ?>
						<div class="signature"><?php __($reply[$k]['signature']) ?></div>
					<?php endif; ?>
				</div>
				<div class="footer">
					<div class="fleft">
						<?php if($this->Session->IsMember()): ?>
							<a href="report/post/<?php __($reply[$k]['p_id']) ?>" class="small-button grey fancybox fancybox.ajax"><?php __("T_REPORT_POST") ?></a>
						<?php endif; ?>
					</div>
					<div class="fright">
						<?php __($reply[$k]['post_controls']) ?>
						<?php __($reply[$k]['thread_controls']) ?>
					</div>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	<div class="box center"><?php __("T_NO_REPLIES") ?></div>
<?php endif; ?>

<!-- PAGINATION -->

<div class="thread-buttons">
	<div class="fleft"><?php __($pagination) ?></div>
	<div class="fright">
		<?php if($this->Session->IsMember()): ?>
			<?php if($thread_info['obsolete']): ?>
				<a href="javascript:void()" class="default-button disabled"><?php __("T_BTN_OBSOLETE") ?></a>
			<?php elseif($thread_info['locked'] == 0 && $thread_info['allow_to_reply']): ?>
				<a href="thread/reply/<?php __($thread_id) ?>" class="default-button"><?php __("T_BTN_ADD") ?></a>
			<?php else: ?>
				<a href="javascript:void()" class="default-button disabled"><?php __("T_BTN_LOCKED") ?></a>
			<?php endif; ?>
		<?php endif; ?>
	</div>
</div>

<!-- MODERATION OPTIONS -->

<?php if($is_moderator): ?>
	<div class="thread-moderation">
		<a href="" class="title"><i class="fa fa-fw fa-angle-down"></i><?php __("T_MOD_OPTIONS") ?></a>
		<div class="box">
			<?php if($thread_info['locked'] == 0): ?>
				<a href="thread/lock/<?php __($thread_id) ?>"><i class="fa fa-fw fa-lock"></i><?php __("T_MOD_LOCK_THREAD") ?></a>
			<?php else: ?>
				<a href="thread/unlock/<?php __($thread_id) ?>"><i class="fa fa-fw fa-unlock"></i><?php __("T_MOD_UNLOCK_THREAD") ?></a>
			<?php endif; ?>
			<?php if($thread_info['announcement'] == 0): ?>
				<a href="thread/announcement_set/<?php __($thread_id) ?>"><i class="fa fa-fw fa-thumb-tack"></i><?php __("T_MOD_SET_ANNOUNCEMENT") ?></a>
			<?php else: ?>
				<a href="thread/announcement_unset/<?php __($thread_id) ?>"><i class="fa fa-fw fa-thumb-tack"></i><?php __("T_MOD_UNSET_ANNOUNCEMENT") ?></a>
			<?php endif; ?>
			<a href="thread/delete/<?php __($thread_id) ?>" id="thread-delete" data-confirm="<?php __("T_MOD_DELETE_MESSAGE") ?>"><i class="fa fa-fw fa-times-circle"></i><?php __("T_MOD_DELETE_THREAD") ?></a>
		</div>
	</div>
<?php endif; ?>

<!-- RELATED THREADS -->

<div class="thread-related">
	<h2><?php __("T_RELATED") ?></h2>
	<?php if($related_thread_list): ?>
		<?php foreach($related_thread_list as $k => $v): ?>
			<div class="item">
				<span><?php __($related_thread_list[$k]['thread_date']) ?></span>
				<a href="thread/<?php __($related_thread_list[$k]['t_id'] . "-" . $related_thread_list[$k]['slug']) ?>">
					<?php __($related_thread_list[$k]['title']) ?>
				</a>
			</div>
		<?php endforeach; ?>
	<?php else: ?>
		<div class="item"><span><?php __("T_NO_RELATED") ?></span></div>
	<?php endif; ?>
</div>

<!-- DELETE POST LIGHTBOX -->

<div id="deleteThreadConfirm" style="display: none">
	<form action="thread/delete_post" method="post" class="validate">
		<table class="table-list no-borders" style="width:350px; margin:0">
			<tr>
				<th>
					<div class="fleft"><?php __("T_DELETE_POST") ?></div>
					<div class="fright"><a href="javascript:jQuery.fancybox.close();" class="small-button grey white transition"><?php __("T_CLOSE") ?></a></div>
				</th>
			</tr>
			<tr>
				<td class="min"><?php __("T_DELETE_NOTICE") ?></td>
			</tr>
			<tr class="footer">
				<td colspan="2" style="text-align:center; padding:10px">
					<input type="hidden" name="pid" id="delete_post_id" value="">
					<input type="hidden" name="tid" id="delete_thread_id" value="">
					<input type="hidden" name="mid" id="delete_member_id" value="">
					<input type="submit" value="<?php __("T_DELETE_POST") ?>">
				</td>
			</tr>
		</table>
	</form>
</div>
