<div class="title-bar">
	<div class="title">
		<span><?php __($community_name) ?></span>
		<?php __("P_EDIT_POST") ?>: <?php echo $thread_info['title'] ?>
	</div>
</div>

<div class="box">
	<form action="thread/save_edit/<?php echo $post_info['p_id'] ?>" method="post" class="validate" enctype="multipart/form-data">
		<div class="input-box">
			<div class="label"><?php __("P_POST") ?></div>
			<div class="field">
				<textarea name="post" id="post" class="full" rows="12"><?php __($post_info['post']) ?></textarea>
			</div>
		</div>
		<div class="fleft">
			<div class="error-message"><?php __("P_ERROR") ?></div>
		</div>
		<div class="fright">
			<input type="hidden" name="thread_id" value="<?php __($post_info['thread_id']) ?>">
			<input type="submit" value="<?php __("T_EDIT") ?>">
		</div>
	</form>
</div>
