<h1>
	<small><?= $community_name ?></small>
	<?php __("thread.add.new_thread") ?>: <?= $room_info['name'] ?>
</h1>

<div class="block">
	<form action="thread/savethread/<?= $room_info['r_id'] ?>" method="post" enctype="multipart/form-data">
		<div class="form-group grid">
			<label for="" class="col-2"><?php __("thread.add.title") ?></label>
			<div class="col-6">
				<input type="text" name="title" class="form-control" maxlength="60" required>
			</div>
		</div>
		<div class="form-group grid">
			<label for="" class="col-2"><?php __("thread.add.post") ?></label>
			<div class="col-10">
				<textarea name="post" id="post" rows="30"></textarea>
			</div>
		</div>
		<?php if($is_poll): ?>
			<div class="form-group grid">
				<label for="" class="col-2"><?php __("thread.add.poll.question") ?></label>
				<div class="col-6">
					<input type="text" name="poll_question" class="form-control" maxlength="60" required>
				</div>
			</div>
			<div class="form-group grid">
				<label for="" class="col-2">
					<?php __("thread.add.poll.choices") ?>
					<small><?php __("thread.add.poll.description") ?></small>
				</label>
				<div class="col-6">
					<textarea name="poll_choices" rows="8" class="form-control" style="margin-bottom: 15px" required></textarea>
					<label class="checkbox-control">
						<input type="checkbox" name="poll_allow_multiple"><span><i class="fa fa-check"></i></span>
						<?php __("thread.add.poll.allow_multiple") ?>
					</label>
				</div>
			</div>
		<?php endif; ?>
		<?php if($allow_uploads): ?>
			<div class="form-group grid">
				<label for="" class="col-2"><?php __("thread.attachments") ?></label>
				<div class="col-6">
					<input type="file" name="attachment">
				</div>
			</div>
		<?php endif; ?>
		<?php if($member_info['usergroup'] == 1 || $member_info['usergroup'] == 2 || $is_moderator): ?>
			<div class="form-group grid">
				<label for="" class="col-2"><?php __("thread.add.options") ?></label>
				<div class="col-10">
					<label class="checkbox-control">
						<input type="hidden" name="announcement" value="0">
						<input type="checkbox" name="announcement" value="1"><span><i class="fa fa-check"></i></span>
						<?php __("thread.add.set_announcement") ?>
					</label>
					<label class="checkbox-control">
						<input type="hidden" name="locked" value="0">
						<input type="checkbox" name="locked" value="1"><span><i class="fa fa-check"></i></span>
						<?php __("thread.add.locked") ?>
					</label>
					<div class="thread-schedule">
						<div class="thread-schedule-title" data-toggle="thread-schedule-content">
							<i class="fa fa-fw fa-angle-right"></i> <?php __("thread.add.auto.title") ?>
						</div>
						<div class="thread-schedule-content" id="thread-schedule-content">
							<?php __("thread.add.auto.description") ?>
							<small><?= $thread_auto_details ?></small>
							<label>
								<div><?php __("thread.add.auto.open_at") ?></div>
								<?php
									echo \AC\Kernel\Html::days("open_day", 0, true) . "&nbsp;";
									echo \AC\Kernel\Html::months("open_month", false, 0, true) . "&nbsp;";
									echo \AC\Kernel\Html::years("open_year", 0, 2, 0, true) . " at ";
									echo \AC\Kernel\Html::hours("open_hours", 0) . " : ";
									echo \AC\Kernel\Html::minutes("open_minutes", 0);
								?>
							</label>
							<label>
								<div><?php __("thread.add.auto.lock_at") ?></div>
								<?php
									echo \AC\Kernel\Html::days("lock_day", 0, true) . "&nbsp;";
									echo \AC\Kernel\Html::months("lock_month", false, 0, true) . "&nbsp;";
									echo \AC\Kernel\Html::years("lock_year", 0, 2, 0, true) . " at ";
									echo \AC\Kernel\Html::hours("lock_hours", 0) . " : ";
									echo \AC\Kernel\Html::minutes("lock_minutes", 0);
								?>
							</label>
						</div>
					</div>
				</div>
			</div>
		<?php endif; ?>
		<div class="pull-clear">
			<div class="pull-left">
				<div class="error-message"><?php __("thread.notification.title_post_empty") ?></div>
			</div>
			<div class="pull-right">
				<input type="hidden" name="room_id" value="<?= $room_info['r_id'] ?>">
				<input type="submit" value="<?php __("thread.add.add_new_thread") ?>" class="btn btn-default">
			</div>
		</div>
	</form>
</div>
