<h1>
	<small><?= $community_name ?></small>
	<?php __("P_NEW_THREAD") ?>: <?= $room_info['name'] ?>
</h1>

<div class="block">
	<form action="thread/savethread/<?= $room_info['r_id'] ?>" method="post" enctype="multipart/form-data">
		<div class="form-group grid">
			<label for="" class="col-2"><?php __("P_THREAD_TITLE") ?></label>
			<div class="col-6">
				<input type="text" name="title" class="form-control" maxlength="60" required>
			</div>
		</div>
		<div class="form-group grid">
			<label for="" class="col-2"><?php __("P_POST") ?></label>
			<div class="col-10">
				<textarea name="post" id="post" rows="30"></textarea>
			</div>
		</div>
		<?php if($is_poll): ?>
			<div class="form-group grid">
				<label for="" class="col-2"><?php __("P_POLL_QUESTION") ?></label>
				<div class="col-6">
					<input type="text" name="poll_question" class="form-control" maxlength="60" required>
				</div>
			</div>
			<div class="form-group grid">
				<label for="" class="col-2">
					<?php __("P_POLL_CHOICES") ?>
					<small><?php __("P_POLL_CHOICES_DESC") ?></small>
				</label>
				<div class="col-6">
					<textarea name="poll_choices" rows="8" class="form-control" style="margin-bottom: 15px" required></textarea>
					<label class="checkbox-control">
						<input type="checkbox" name="poll_allow_multiple"><span><i class="fa fa-check"></i></span>
						<?php __("P_POLL_ALLOW_MULTIPLE") ?>
					</label>
				</div>
			</div>
		<?php endif; ?>
		<?php if($allow_uploads): ?>
			<div class="form-group grid">
				<label for="" class="col-2"><?php __("P_ATTACHMENTS") ?></label>
				<div class="col-6">
					<input type="file" name="attachment">
				</div>
			</div>
		<?php endif; ?>
		<?php if($member_info['usergroup'] == 1 || $member_info['usergroup'] == 2 || $is_moderator): ?>
			<div class="form-group grid">
				<label for="" class="col-2"><?php __("P_OPTIONS") ?></label>
				<div class="col-10">
					<label class="checkbox-control">
						<input type="hidden" name="announcement" value="0">
						<input type="checkbox" name="announcement" value="1"><span><i class="fa fa-check"></i></span>
						<?php __("P_SET_ANNOUNCEMENT") ?>
					</label>
					<label class="checkbox-control">
						<input type="hidden" name="locked" value="0">
						<input type="checkbox" name="locked" value="1"><span><i class="fa fa-check"></i></span>
						<?php __("P_LOCK") ?>
					</label>
					<div class="thread-schedule">
						<div class="thread-schedule-title" data-toggle="thread-schedule-content">
							<i class="fa fa-fw fa-angle-right"></i> <?php __("T_AUTO_TITLE") ?>
						</div>
						<div class="thread-schedule-content" id="thread-schedule-content">
							<?php __("T_AUTO_DESCRIPTION") ?>
							<small><?= $thread_auto_details ?></small>
							<label>
								<div><?php __("T_AUTO_OPEN_AT") ?></div>
								<?php
									__(\AC\Kernel\Html::Days("open_day", 0, true) . "&nbsp;");
									__(\AC\Kernel\Html::Months("open_month", false, 0, true) . "&nbsp;");
									__(\AC\Kernel\Html::Years("open_year", 0, 2, 0, true) . " at ");
									__(\AC\Kernel\Html::Hours("open_hours", 0) . " : ");
									__(\AC\Kernel\Html::Minutes("open_minutes", 0));
								?>
							</label>
							<label>
								<div><?php __("T_AUTO_CLOSE_AT") ?></div>
								<?php
									__(\AC\Kernel\Html::Days("lock_day", 0, true) . "&nbsp;");
									__(\AC\Kernel\Html::Months("lock_month", false, 0, true) . "&nbsp;");
									__(\AC\Kernel\Html::Years("lock_year", 0, 2, 0, true) . " at ");
									__(\AC\Kernel\Html::Hours("lock_hours", 0) . " : ");
									__(\AC\Kernel\Html::Minutes("lock_minutes", 0));
								?>
							</label>
						</div>
					</div>
				</div>
			</div>
		<?php endif; ?>
		<div class="pull-clear">
			<div class="pull-left">
				<div class="error-message"><?php __("P_NEW_ERROR") ?></div>
			</div>
			<div class="pull-right">
				<input type="hidden" name="room_id" value="<?= $room_info['r_id'] ?>">
				<input type="submit" value="<?php __("P_NEW_THREAD_SUBMIT") ?>" class="btn btn-default">
			</div>
		</div>
	</form>
</div>
