<h1>
	<small><?= $community_name ?></small>
	<?php __("usercp.title") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?= $menu[0] ?>"><?php __("usercp.summary.title") ?></a>
			<a href="usercp/profile" class="<?= $menu[1] ?>"><?php __("usercp.profile.title") ?></a>
			<a href="usercp/avatar" class="<?= $menu[2] ?>"><?php __("usercp.avatar.title") ?></a>
			<a href="usercp/cover" class="<?= $menu[3] ?>"><?php __("usercp.cover.title") ?></a>
			<a href="usercp/signature" class="<?= $menu[4] ?>"><?php __("usercp.signature.title") ?></a>
			<a href="usercp/settings" class="<?= $menu[5] ?>"><?php __("usercp.settings.title") ?></a>
			<a href="usercp/password" class="<?= $menu[6] ?>"><?php __("usercp.password.title") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?= $notification ?>
		<form action="usercp/save_password" method="post">
			<div class="form-group grid">
				<label class="col-3"><?php __("usercp.password.current") ?></label>
				<div class="col-4">
					<input type="password" name="current" class="form-control" required>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-3"><?php __("usercp.password.new") ?></label>
				<div class="col-4">
					<input type="password" name="new_password" class="form-control" required>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-3"><?php __("usercp.password.retype") ?></label>
				<div class="col-4">
					<input type="password" name="conf_password" class="form-control" required>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-left">
				<div class="error-message"><?php __("usercp.password.empty") ?></div>
				</div>
				<div class="pull-right">
					<input type="submit" value="<?php __("usercp.password.change") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>
