<h1>
	<small><?= $community_name ?></small>
	<?php __("usercp.title") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?= $menu[0] ?>"><?php __("usercp.summary.title") ?></a>
			<a href="usercp/profile" class="<?= $menu[1] ?>"><?php __("usercp.profile.title") ?></a>
			<a href="usercp/avatar" class="<?= $menu[2] ?>"><?php __("usercp.avatar.title") ?></a>
			<a href="usercp/cover" class="<?= $menu[3] ?>"><?php __("usercp.cover.title") ?></a>
			<a href="usercp/signature" class="<?= $menu[4] ?>"><?php __("usercp.signature.title") ?></a>
			<a href="usercp/settings" class="<?= $menu[5] ?>"><?php __("usercp.settings.title") ?></a>
			<a href="usercp/password" class="<?= $menu[6] ?>"><?php __("usercp.password.title") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?= $notification ?>
		<form action="usercp/save_photo" method="post" enctype="multipart/form-data">
			<div class="form-group grid">
				<label class="col-3"><?php __("usercp.avatar.source") ?></label>
				<div class="col-9">
					<label class="radio-control">
						<input type="radio" name="photo_type" class="photo-select" value="gravatar" <?= $photo_info['gravatar'] ?>><span></span>
						Gravatar
					</label>
					<?php if($enable_upload): ?>
						<label class="radio-control">
							<input type="radio" name="photo_type" class="photo-select" value="custom" <?= $photo_info['custom'] ?>><span></span>
							<?php __("usercp.avatar.custom") ?>
						</label>
					<?php endif; ?>
				</div>
			</div>

			<!-- GRAVATAR -->
			<div class="form-group grid" id="gravatar" style="display: none">
				<label class="col-3"><?php __("usercp.avatar.gravatar_settings") ?></label>
				<div class="col-9">
					<div class="pull-left" style="margin-right: 20px">
						<?= \AC\Kernel\Html::crop($photo_info['gravatar_image'], 120) ?>
					</div>
					<p><?php __("usercp.avatar.gravatar_message") ?></p>
				</div>
			</div>

			<!-- CUSTOM -->
			<div class="form-group grid" id="custom" style="display: none">
				<label class="col-3"><?php __("usercp.avatar.upload") ?></label>
				<div class="col-9">
					<div class="pull-left custom-photo-placeholder" style="margin-right: 20px">
						<?= \AC\Kernel\Html::crop($photo_info['custom_image'], 120) ?>
					</div>
					<div class="pull-left" style="width: 400px">
						<input type="file" name="file_upload">
					</div>
				</div>
			</div>

			<div class="pull-clear">
				<div class="pull-right">
					<input type="submit" value="<?php __("usercp.avatar.update") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>
