<h1>
	<small><?= $community_name ?></small>
	<?php __("C_TITLE") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?php __($menu[0]) ?>"><?php __("C_SUMMARY") ?></a>
			<a href="usercp/profile" class="<?php __($menu[1]) ?>"><?php __("C_PROFILE") ?></a>
			<a href="usercp/avatar" class="<?php __($menu[2]) ?>"><?php __("C_PHOTO") ?></a>
			<a href="usercp/cover" class="<?php __($menu[3]) ?>"><?php __("C_COVER") ?></a>
			<a href="usercp/signature" class="<?php __($menu[4]) ?>"><?php __("C_SIGNATURE") ?></a>
			<a href="usercp/settings" class="<?php __($menu[5]) ?>"><?php __("C_SETTINGS") ?></a>
			<a href="usercp/password" class="<?php __($menu[6]) ?>"><?php __("C_PASSWORD") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?= $notification ?>
		<form action="usercp/save_photo" method="post" enctype="multipart/form-data">
			<div class="form-group grid">
				<label class="col-3"><?php __("C_PHOTO_SOURCE") ?></label>
				<div class="col-9">
					<label class="radio-control">
						<input type="radio" name="photo_type" class="photo-select" value="gravatar" <?= $photo_info['gravatar'] ?>><span></span>
						Gravatar
					</label>
					<?php if($enable_upload): ?>
						<label class="radio-control">
							<input type="radio" name="photo_type" class="photo-select" value="custom" <?= $photo_info['custom'] ?>><span></span>
							<?php __("C_PHOTO_CUSTOM") ?>
						</label>
					<?php endif; ?>
				</div>
			</div>

			<!-- GRAVATAR -->
			<div class="form-group grid" id="gravatar" style="display: none">
				<label class="col-3"><?php __("C_GRAVATAR_SETTINGS") ?></label>
				<div class="col-9">
					<div class="pull-left" style="margin-right: 20px">
						<?= \AC\Kernel\Html::crop($photo_info['gravatar_image'], 120) ?>
					</div>
					<p><?php __("C_GRAVATAR_MESSAGE") ?></p>
				</div>
			</div>

			<!-- CUSTOM -->
			<div class="form-group grid" id="custom" style="display: none">
				<label class="col-3"><?php __("C_PHOTO_UPLOAD") ?></label>
				<div class="col-9">
					<div class="pull-left custom-photo-placeholder" style="margin-right: 20px">
						<?= \AC\Kernel\Html::crop($photo_info['custom_image'], 120) ?>
					</div>
					<div class="pull-left" style="width: 400px">
						<input type="file" name="file_upload">
					</div>
				</div>
			</div>

			<div class="pull-clear">
				<div class="pull-right">
					<input type="submit" value="<?php __("C_UPDATE_PHOTO") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>
