<h1>
	<small><?= $community_name ?></small>
	<?php __("usercp.title") ?>
</h1>

<div class="block padding-no">
	<div class="nav">
		<div class="nav-top">
			<a href="usercp" class="<?= $menu[0] ?>"><?php __("usercp.summary.title") ?></a>
			<a href="usercp/profile" class="<?= $menu[1] ?>"><?php __("usercp.profile.title") ?></a>
			<a href="usercp/avatar" class="<?= $menu[2] ?>"><?php __("usercp.avatar.title") ?></a>
			<a href="usercp/cover" class="<?= $menu[3] ?>"><?php __("usercp.cover.title") ?></a>
			<a href="usercp/signature" class="<?= $menu[4] ?>"><?php __("usercp.signature.title") ?></a>
			<a href="usercp/settings" class="<?= $menu[5] ?>"><?php __("usercp.settings.title") ?></a>
			<a href="usercp/password" class="<?= $menu[6] ?>"><?php __("usercp.password.title") ?></a>
		</div>
	</div>
	<div class="block-nav-content">
		<h2><?php __("usercp.summary.account_summary") ?></h2>
		<table class="table">
			<tbody>
				<tr>
					<td class="min text-muted"><?php __("usercp.summary.total_posts") ?></td>
					<td><?php __("usercp.summary.posts", $posts_total) ?></td>
				</tr>
				<tr>
					<td class="min text-muted"><?php __("usercp.summary.registered") ?></td>
					<td><?= $register_date ?></td>
				</tr>
				<tr>
					<td class="min text-muted"><?php __("usercp.summary.average_posts") ?></td>
					<td><?php __("usercp.summary.posts_per_day", $posts_average) ?></td>
				</tr>
			</tbody>
		</table>
		<h2><?php __("usercp.summary.messenger_summary") ?></h2>
		<table class="table">
			<tbody>
				<tr>
					<td class="min text-muted"><?php __("usercp.summary.total_messages") ?></td>
					<td><?= $pm_total ?> <?php __("usercp.summary.messages") ?></td>
				</tr>
				<tr>
					<td class="min text-muted"><?php __("usercp.summary.space_left") ?></td>
					<td><?= $pm_space_left ?></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
