<h1>
	<small><?php echo $community_name ?></small>
	<?php __("C_TITLE") ?>
</h1>

<div class="block no-padding">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?php __($menu[0]) ?>"><?php __("C_SUMMARY") ?></a>
			<a href="usercp/profile" class="<?php __($menu[1]) ?>"><?php __("C_PROFILE") ?></a>
			<a href="usercp/photo" class="<?php __($menu[2]) ?>"><?php __("C_PHOTO") ?></a>
			<a href="usercp/signature" class="<?php __($menu[3]) ?>"><?php __("C_SIGNATURE") ?></a>
			<a href="usercp/settings" class="<?php __($menu[4]) ?>"><?php __("C_SETTINGS") ?></a>
			<a href="usercp/password" class="<?php __($menu[5]) ?>"><?php __("C_PASSWORD") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?php __($notification) ?>
		<form action="usercp/save_signature" method="post">
			<div class="form-group grid">
				<label for="teste" class="col-2"><?php __("C_SIGNATURE_EDIT") ?></label>
				<div class="col-10">
					<textarea name="signature" class="signature" id="signature" rows="10"><?php echo $member_info['signature'] ?></textarea>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-right">
					<input type="submit" value="<?php __("C_SIGNATURE_UPDATE") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>
