<h1>
	<small><?= $community_name ?></small>
	<?php __("C_TITLE") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?php __($menu[0]) ?>"><?php __("C_SUMMARY") ?></a>
			<a href="usercp/profile" class="<?php __($menu[1]) ?>"><?php __("C_PROFILE") ?></a>
			<a href="usercp/photo" class="<?php __($menu[2]) ?>"><?php __("C_PHOTO") ?></a>
			<a href="usercp/signature" class="<?php __($menu[3]) ?>"><?php __("C_SIGNATURE") ?></a>
			<a href="usercp/settings" class="<?php __($menu[4]) ?>"><?php __("C_SETTINGS") ?></a>
			<a href="usercp/password" class="<?php __($menu[5]) ?>"><?php __("C_PASSWORD") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?php __($notification) ?>
		<form action="usercp/save_profile" method="post">
			<div class="form-group grid">
				<label class="col-2"><?php __("C_MEMBER_TITLE") ?></label>
				<div class="col-4">
					<input type="text" name="member_title" class="form-control" value="<?= $member['member_title'] ?>">
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_ABOUT_ME") ?></label>
				<div class="col-6">
					<textarea name="profile" rows="4" class="form-control"><?= $member['profile'] ?></textarea>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_EMAIL_ADDR") ?></label>
				<div class="col-5">
					<input type="email" name="email" class="form-control" value="<?= $member['email'] ?>">
				</div>
				<div class="col-5 form-control-static">
					<label class="checkbox-control">
						<input type="hidden" name="hide_email" value="0">
						<input type="checkbox" name="hide_email" value="1" <?php __($profile['hide_email_status']) ?>>
						<span><i class="fa fa-check"></i></span>
						<small><?php __("C_EMAIL_HIDE") ?></small>
					</label>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_BIRTHDATE") ?></label>
				<div class="col-10">
					<?php
						echo \AC\Kernel\Html::days("b_day", $member['b_day'], true) . " ";
						echo \AC\Kernel\Html::months("b_month", false, $member['b_month'], true) . " ";
						echo \AC\Kernel\Html::years("b_year", 80, 0, $member['b_year'], true);
					?>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_GENDER") ?></label>
				<div class="col-10">
					<select name="gender" class="select2-no-search" style="width: 120px">
						<option value="0">---</option>
						<option value="M" <?php __($profile['male']) ?>><?php __("C_GENDER_MALE") ?></option>
						<option value="F" <?php __($profile['female']) ?>><?php __("C_GENDER_FEMALE") ?></option>
					</select>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_LOCATION") ?></label>
				<div class="col-4">
					<input type="text" name="location" class="form-control" value="<?= $member['location'] ?>">
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_WEBSITE") ?></label>
				<div class="col-5">
					<input type="url" name="website" class="form-control" value="<?= $member['website'] ?>">
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2">Facebook</label>
				<div class="col-4">
					<div class="input-group">
						<div class="input-group-addon">fb.me/</div>
						<input type="text" name="im_facebook" class="form-control" value="<?= $member['im_facebook'] ?>">
					</div>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2">Twitter</label>
				<div class="col-3">
					<div class="input-group">
						<div class="input-group-addon"><i class="fa fa-at"></i></div>
						<input type="text" name="im_twitter" class="form-control" value="<?= $member['im_twitter'] ?>">
					</div>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-right">
					<input type="submit" value="<?php __("C_UPDATE_PROFILE") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>
