<h1>
	<small><?php echo $community_name ?></small>
	<?php __("C_TITLE") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?php __($menu[0]) ?>"><?php __("C_SUMMARY") ?></a>
			<a href="usercp/profile" class="<?php __($menu[1]) ?>"><?php __("C_PROFILE") ?></a>
			<a href="usercp/photo" class="<?php __($menu[2]) ?>"><?php __("C_PHOTO") ?></a>
			<a href="usercp/signature" class="<?php __($menu[3]) ?>"><?php __("C_SIGNATURE") ?></a>
			<a href="usercp/settings" class="<?php __($menu[4]) ?>"><?php __("C_SETTINGS") ?></a>
			<a href="usercp/password" class="<?php __($menu[5]) ?>"><?php __("C_PASSWORD") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?php __($notification) ?>
		<form action="usercp/save_password" method="post">
			<div class="form-group grid">
				<label for="teste" class="col-3"><?php __("C_PASSWORD_CURRENT") ?></label>
				<div class="col-4">
					<input type="password" name="current" class="form-control" required>
				</div>
			</div>
			<div class="form-group grid">
				<label for="teste" class="col-3"><?php __("C_PASSWORD_NEW") ?></label>
				<div class="col-4">
					<input type="password" name="new_password" class="form-control" required>
				</div>
			</div>
			<div class="form-group grid">
				<label for="teste" class="col-3"><?php __("C_PASSWORD_RETYPE") ?></label>
				<div class="col-4">
					<input type="password" name="conf_password" class="form-control" required>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-left">
				<div class="error-message"><?php __("C_PASSWORD_EMPTY") ?></div>
				</div>
				<div class="pull-right">
					<input type="submit" value="<?php __("C_CHANGE_PASSWORD") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>

<!--
<div class="box no-shadow">
	<?php __($notification) ?>
	<form action="usercp/save_password" method="post" class="validate">
		<div class="input-box">
			<div class="label"><?php __("C_PASSWORD_CURRENT") ?></div>
			<div class="field"><input type="password"="current" class="required small"></div>
		</div>
		<div class="input-box">
			<div class="label"><?php __("C_PASSWORD_NEW") ?></div>
			<div class="field"><input type="password" name="new_password" class="required small"></div>
		</div>
		<div class="input-box">
			<div class="label"><?php __("C_PASSWORD_RETYPE") ?></div>
			<div class="field"><input type="password" name="conf_password" class="required small"></div>
		</div>
		<div class="fleft">
			<div class="error-message"><?php __("C_PASSWORD_EMPTY") ?></div>
		</div>
		<div class="fright"><input type="submit" value="<?php __("C_CHANGE_PASSWORD") ?>"></div>
	</form>
</div>
-->
