<h1>
	<small><?= $community_name ?></small>
	<?php __("C_TITLE") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?php __($menu[0]) ?>"><?php __("C_SUMMARY") ?></a>
			<a href="usercp/profile" class="<?php __($menu[1]) ?>"><?php __("C_PROFILE") ?></a>
			<a href="usercp/avatar" class="<?php __($menu[2]) ?>"><?php __("C_PHOTO") ?></a>
			<a href="usercp/cover" class="<?php __($menu[3]) ?>"><?php __("C_COVER") ?></a>
			<a href="usercp/signature" class="<?php __($menu[4]) ?>"><?php __("C_SIGNATURE") ?></a>
			<a href="usercp/settings" class="<?php __($menu[5]) ?>"><?php __("C_SETTINGS") ?></a>
			<a href="usercp/password" class="<?php __($menu[6]) ?>"><?php __("C_PASSWORD") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?= $notification ?>
		<form action="usercp/save_settings" method="post">
			<div class="form-group grid">
				<label class="col-2"><?php __("C_TIMEZONE") ?></label>
				<div class="col-10">
					<select name="timezone" class="select2" style="width: 600px">
						<?php __($settings['tz_list']) ?>
					</select>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_LANGUAGE") ?></label>
				<div class="col-10">
					<select name="language" class="select2-no-search" style="width: 200px">
						<?php __($settings['lang_list']) ?>
					</select>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("C_THEME") ?></label>
				<div class="col-10">
					<select name="theme" class="select2-no-search" style="width: 200px">
						<?php __($settings['theme_list']) ?>
					</select>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-right">
					<input type="submit" value="<?php __("C_UPDATE_SETTINGS") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>


<!--
<div class="box no-shadow">
	<?php __($notification) ?>
	<form action="usercp/save_settings" method="post" class="validate">
		<div class="input-box">
			<div class="label"><?php __("C_TIMEZONE") ?></div>
			<div class="field">
				<select name="timezone" class="select2" style="width:500px">
					<?php __($settings['tz_list']) ?>
				</select>
			</div>
		</div>
		<div class="input-box">
			<div class="label"><?php __("C_LANGUAGE") ?></div>
			<div class="field">
				<select name="language" class="select2-no-search" style="width: 180px">
					<?php __($settings['lang_list']) ?>
				</select>
			</div>
		</div>
		<div class="input-box">
			<div class="label"><?php __("C_THEME") ?></div>
			<div class="field">
				<select name="theme" class="select2-no-search" style="width: 180px">
					<?php __($settings['theme_list']) ?>
				</select>
			</div>
		</div>
		<div class="fright"><input type="submit" value="<?php __("C_UPDATE_SETTINGS") ?>"></div>
	</form>
</div>
-->
