<h1>
	<small><?= $community_name ?></small>
	<?php __("usercp.title") ?>
</h1>

<div class="block padding-no">
	<div class="nav room-nav">
		<div class="nav-top">
			<a href="usercp" class="<?= $menu[0] ?>"><?php __("usercp.summary.title") ?></a>
			<a href="usercp/profile" class="<?= $menu[1] ?>"><?php __("usercp.profile.title") ?></a>
			<a href="usercp/avatar" class="<?= $menu[2] ?>"><?php __("usercp.avatar.title") ?></a>
			<a href="usercp/cover" class="<?= $menu[3] ?>"><?php __("usercp.cover.title") ?></a>
			<a href="usercp/signature" class="<?= $menu[4] ?>"><?php __("usercp.signature.title") ?></a>
			<a href="usercp/settings" class="<?= $menu[5] ?>"><?php __("usercp.settings.title") ?></a>
			<a href="usercp/password" class="<?= $menu[6] ?>"><?php __("usercp.password.title") ?></a>
		</div>
	</div>
	<div class="block-nav-content padding-10">
		<?= $notification ?>
		<form action="usercp/save_settings" method="post">
			<div class="form-group grid">
				<label class="col-2"><?php __("usercp.settings.timezone") ?></label>
				<div class="col-10">
					<select name="timezone" class="select2" style="width: 600px">
						<?= $settings['tz_list'] ?>
					</select>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("usercp.settings.language") ?></label>
				<div class="col-10">
					<select name="language" class="select2-no-search" style="width: 200px">
						<?= $settings['lang_list'] ?>
					</select>
				</div>
			</div>
			<div class="form-group grid">
				<label class="col-2"><?php __("usercp.settings.theme") ?></label>
				<div class="col-10">
					<select name="theme" class="select2-no-search" style="width: 200px">
						<?= $settings['theme_list'] ?>
					</select>
				</div>
			</div>
			<div class="pull-clear">
				<div class="pull-right">
					<input type="submit" value="<?php __("usercp.settings.update") ?>" class="btn btn-default">
				</div>
			</div>
		</form>
	</div>
</div>
