<div class="title-bar">
	<div class="title fleft">
		<span><?php __($community_name) ?></span><?php __("C_TITLE") ?>
	</div>
</div>

<div class="navigation">
	<div class="navbar">
		<a href="usercp" class="<?php __($menu[0]) ?>"><?php __("C_PROFILE") ?></a>
		<a href="usercp/photo" class="<?php __($menu[1]) ?>"><?php __("C_PHOTO") ?></a>
		<a href="usercp/signature" class="<?php __($menu[2]) ?>"><?php __("C_SIGNATURE") ?></a>
		<a href="usercp/settings" class="<?php __($menu[3]) ?>"><?php __("C_SETTINGS") ?></a>
		<a href="usercp/password" class="<?php __($menu[4]) ?>"><?php __("C_PASSWORD") ?></a>
	</div>
</div>

<div class="box no-shadow">
	<?php __($notification) ?>
	<form action="usercp/save_photo" method="post" class="validate" enctype="multipart/form-data">
		<div class="input-box">
			<div class="label"><?php __("C_PHOTO_SOURCE") ?></div>
			<div class="field">
				<input type="radio" name="photo_type" class="photoSelect" value="gravatar" <?php __($photo_info['gravatar']) ?>> Gravatar<br>
				<input type="radio" name="photo_type" class="photoSelect" value="facebook" <?php __($photo_info['facebook']) ?>> Facebook<br>
				<?php if($enable_upload == "true"): ?>
					<input type="radio" name="photo_type" class="photoSelect" value="custom" <?php __($photo_info['custom']) ?>> <?php __("C_PHOTO_CUSTOM") ?>
				<?php endif; ?>
			</div>
		</div>
		<div class="input-box" id="gravatar" style="display: none">
			<div class="label"><?php __("C_GRAVATAR_SETTINGS") ?></div>
			<div class="field">
				<div class="fleft" style="margin-right: 15px">
					<?php __(Html::Crop($photo_info['gravatar_image'], 120, 120)) ?>
				</div>
				<div class="fleft">
					<?php __("C_GRAVATAR_MESSAGE") ?>
				</div>
				<div class="fix"></div>
			</div>
		</div>
		<div class="input-box" id="facebook" style="display: none">
			<div class="label"><?php __("C_FACEBOOK_SETTINGS") ?></div>
			<div class="field">
				<div class="fleft" style="margin-right: 15px">
					<?php __(Html::Crop($photo_info['facebook_image'], 120, 120)) ?>
				</div>
				<div class="fleft">
					<?php __("C_FACEBOOK_MESSAGE") ?>
				</div>
				<div class="fix"></div>
			</div>
		</div>
		<div class="input-box" id="custom" style="display: none">
			<div class="label"><?php __("C_PHOTO_UPLOAD") ?></div>
			<div class="field">
				<div class="fleft" style="margin-right: 15px">
					<?php __(Html::Crop("public/avatar/" . $member_info['photo'], 120, 120)) ?>
				</div>
				<div class="fleft"><input type="file" name="file_upload" class="required"></div>
				<div class="fix"></div>
			</div>
		</div>
		<div class="fright"><input type="submit" value="<?php __("C_UPDATE_PHOTO") ?>"></div>
	</form>
</div>
