<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= $page_title . $community_name ?> (Powered by Addictive Community)</title>
	<base href="<?= $community_url ?>">
	<link rel="search" type="application/opensearchdescription+xml" title="<?= $community_name ?>" href="community/open_search">
	<link rel="shortcut icon" type="image/png" href="favicon.png">

	<!-- Meta Tags -->
	<meta name="generator" content="Addictive Community <?= VERSION ?>">
	<meta name="description" content="<?= $meta_description ?>">

	<!-- Pace -->
	<link rel="stylesheet" href="thirdparty/pace/themes/pace-theme-minimal.css">
	<script src="thirdparty/pace/pace.min.js"></script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="thirdparty/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="thirdparty/fancybox/jquery.fancybox.min.css">
	<link rel="stylesheet" href="thirdparty/select2/css/select2.min.css">
	<link rel="stylesheet" href="static/css/app.min.css">
	<link rel="stylesheet" href="themes/<?= $theme ?>/css/theme.css">

	<script>
		var ROOT = "<?= $community_url ?>";
		var EMOTICON_DIR = "<?= $emoticon_dir ?>";
		var EMOTICONS = [<?php
			$row = [];
			foreach($emoticon_set as $emoticon) {
				$row[] = "[" . implode(", ", $emoticon) . "]";
			}
			echo implode(",", $row);
		?>];
	</script>
</head>
<body>

<header>
	<div class="top-half outer">
		<div class="row space-between">
			<div class="col-flexible">
				<ul class="apps">
					<li><a href="<?= $community_url ?>">Community</a></li>
					<li class="selected"><a href="articles">Articles</a></li>
					<?php if($website_url != "" && $website_url != "http://"): ?>
						<li><a href="<?= $website_url ?>" target="_blank"><?= $website_name ?></a></li>
					<?php endif; ?>
				</ul>
			</div>
			<div class="col-flexible text-right">
				<?php if($is_admin): ?>
					<a href="admin/" target="_blank"><span>Admin CP</span><i class="fa fa-lock"></i></a>
				<?php endif; ?>
				<a href="members"><span><?php __("global.memberlist") ?></span><i class="fa fa-users"></i></a>
				<a href="calendar"><span><?php __("global.calendar") ?></span><i class="fa fa-calendar"></i></a>
				<?php if($member_id == 0): ?>
					<a href="register"><span><?php __("global.create_account") ?></span><i class="fa fa-star"></i></a>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<div class="bottom-half outer">
		<div class="row space-between">
			<div class="col-flexible">
				<a href="<?= $community_url ?>">
					<img src="static/images/logo.svg" class="logo" alt="Addictive Community">
				</a>
			</div>
			<div class="col-minimum nav-button show-sm text-right" id="toggle-sidebar">
				<i class="fa fa-bars"></i>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<ul class="breadcrumb">
					<?= $breadcrumb ?>
				</ul>
			</div>
		</div>
	</div>
</header>

<main class="outer">
	<div class="row content-row margin-no">
		<div class="" id="sidebar">
			<div class="block sidebar">
				<?php if($member_id == 0): ?>
					<div class="block flat user-box">
						<a href="/" class="username">
							<?php __("global.sidebar.welcome") ?>
						</a>
						<ul>
							<li><a href="javascript:;" data-type="ajax" data-src="./login" data-fancybox><?php __("global.sidebar.login") ?></a></li>
							<li><a href="register" class="font-w600"><?php __("global.create_account") ?></a></li>
						</ul>
					</div>
				<?php else: ?>
					<div class="block flat user-box">
						<?= \AC\Kernel\Html::crop($member_info['avatar'], 40, "image") ?>
						<a href="profile/<?= $member_info['m_id'] ?>" class="username">
							<?= $member_info['username'] ?>
						</a>
						<ul>
							<li><a href="usercp"><?php __("global.sidebar.usercp") ?></a></li>
							<li><a href="messenger"><?php __("global.sidebar.inbox", array($unread_messages)) ?></a></li>
							<li><a href="logout"><?php __("global.sidebar.logout") ?></a></li>
						</ul>
					</div>
				<?php endif; ?>
				<?php if($show_members_online): ?>
					<div class="panel">
						<div class="panel-title"><?php __("global.sidebar.members_online") ?></div>
						<div class="panel-content body">
							<dl class="members">
								<dt><?php __("global.sidebar.member_count", array($member_count)) ?></dt>
								<dd><?= $member_list ?></dd>
								<dt><?php __("global.sidebar.guest_count", array($guests_count)) ?></dt>
							</dl>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</div>
		<div id="content">
			<?= $this->content ?>
		</div>
	</div>
</main>

<footer class="text-center">
	Powered by
	<a href="https://github.com/addictivehub/addictive-community" target="_blank">Addictive Community</a>
	<?= VERSION . "-" . CHANNEL ?> &copy; <?= date("Y") ?> - All rights reserved.
</footer>

<!-- JS -->
<script src="thirdparty/jquery/jquery.min.js"></script>
<script src="thirdparty/tinymce/tinymce.min.js"></script>
<script src="thirdparty/fancybox/jquery.fancybox.min.js"></script>
<script src="thirdparty/select2/js/select2.full.min.js"></script>
<script src="static/js/application.js"></script>

</body>
</html>
