<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= $page_title . $community_name ?> (Powered by Addictive Community)</title>
	<base href="<?= $community_url ?>">
	<link rel="search" type="application/opensearchdescription+xml" title="<?= $community_name ?>" href="community/open_search">
	<link rel="shortcut icon" type="image/png" href="favicon.png">

	<!-- Meta Tags -->
	<meta name="generator" content="Addictive Community <?= VERSION ?>">
	<meta name="description" content="<?= $meta_description ?>">

	<!-- Pace -->
	<link rel="stylesheet" href="thirdparty/pace/themes/pace-theme-minimal.css">
	<script src="thirdparty/pace/pace.min.js"></script>

	<!-- CSS Files -->
	<link rel="stylesheet" href="thirdparty/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="thirdparty/fancybox/jquery.fancybox.min.css">
	<link rel="stylesheet" href="thirdparty/select2/css/select2.min.css">
	<link rel="stylesheet" href="static/css/app.min.css">
	<link rel="stylesheet" href="themes/<?= $theme ?>/css/theme.css">

	<script>
		var ROOT = "<?= $community_url ?>";
		var EMOTICON_DIR = "<?= $emoticon_dir ?>";
		var EMOTICONS = [<?php
			$row = [];
			foreach($emoticon_set as $emoticon) {
				$row[] = "[" . implode(", ", $emoticon) . "]";
			}
			echo implode(",", $row);
		?>];
	</script>
</head>
<body>

<div class="outer-container" id="outer-container">
	<div class="inner-container">
		<!-- Header -->
		<?php require_once("templates/default/fragments/_header.phtml"); ?>

		<main class="outer">
			<div class="row content-row margin-no">
				<div class="" id="sidebar">
					<div class="block sidebar">
						<?php if($member_id == 0): ?>
							<div class="block flat user-box">
								<a href="/" class="username">
									<?php __("global.sidebar.welcome") ?>
								</a>
								<ul>
									<li><a href="javascript:;" data-type="ajax" data-src="./login" data-fancybox><?php __("global.sidebar.login") ?></a></li>
									<li><a href="register" class="font-w600"><?php __("global.create_account") ?></a></li>
								</ul>
							</div>
						<?php else: ?>
							<div class="block flat user-box">
								<?= \AC\Kernel\Html::crop($member_info['avatar'], 40, "image") ?>
								<a href="profile/<?= $member_info['m_id'] ?>" class="username">
									<?= $member_info['username'] ?>
								</a>
								<ul>
									<li><a href="usercp"><?php __("global.sidebar.usercp") ?></a></li>
									<li><a href="messenger"><?php __("global.sidebar.inbox", array($unread_messages)) ?></a></li>
									<li><a href="logout"><?php __("global.sidebar.logout") ?></a></li>
								</ul>
							</div>
						<?php endif; ?>
						<div class="panel">
							<div class="panel-title"><?php __("global.sidebar.rooms") ?></div>
							<div class="panel-content">
								<ul class="rooms">
									<?php foreach($sidebar_rooms as $k => $v): ?>
										<li>
											<a href="room/<?= $sidebar_rooms[$k]['r_id'] ?>">
												<?= $sidebar_rooms[$k]['name'] ?>
												<?php if($sidebar_rooms[$k]['password']): ?>
													<span class="badge"><i class="fa fa-lock"></i></span>
												<?php else: ?>
													<span class="badge"><?= $sidebar_rooms[$k]['threads'] ?></span>
												<?php endif; ?>
											</a>
										</li>
									<?php endforeach; ?>
								</ul>
							</div>
						</div>
						<?php if($show_members_online): ?>
							<div class="panel">
								<div class="panel-title"><?php __("global.sidebar.members_online") ?></div>
								<div class="panel-content body">
									<dl class="members">
										<dt><?php __("global.sidebar.member_count", array($member_count)) ?></dt>
										<dd><?= $member_list ?></dd>
										<dt><?php __("global.sidebar.guest_count", array($guests_count)) ?></dt>
									</dl>
								</div>
							</div>
						<?php endif; ?>
						<?php if($show_statistics): ?>
							<div class="panel">
								<div class="panel-title"><?php __("global.sidebar.statistics") ?></div>
								<div class="panel-content body">
									<dl class="stats">
										<dt><?php __("global.sidebar.threads") ?></dt>
										<dd><?= $stats['threads'] ?></dd>
										<dt><?php __("global.sidebar.posts") ?></dt>
										<dd><?= $stats['posts'] ?></dd>
										<dt><?php __("global.sidebar.members") ?></dt>
										<dd><?= $stats['members'] ?></dd>
										<dt><?php __("global.sidebar.last_member") ?></dt>
										<dd>
											<a href="profile/<?= $stats['lastmemberid'] ?>">
												<?= $stats['lastmembername'] ?>
											</a>
										</dd>
									</dl>
								</div>
							</div>
						<?php endif; ?>
					</div>
				</div>
				<div id="content">
					<?= $this->content ?>
				</div>
			</div>
		</main>

		<!-- Footer -->
		<?php require_once("templates/default/fragments/_footer.phtml"); ?>

		<!-- Mobile navigation bar -->
		<?php require_once("templates/default/fragments/_mobile_navigation.phtml"); ?>
	</div>
</div>

<!-- JS -->
<script src="thirdparty/jquery/jquery.min.js"></script>
<script src="thirdparty/tinymce/tinymce.min.js"></script>
<script src="thirdparty/fancybox/jquery.fancybox.min.js"></script>
<script src="thirdparty/select2/js/select2.full.min.js"></script>
<script src="static/js/application.js"></script>

</body>
</html>
