<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php __($page_title . $community_name) ?> (Powered by Addictive Community)</title>
	<base href="<?php __($community_url) ?>">
	<link rel="search" type="application/opensearchdescription+xml" title="<?php __($community_name) ?>" href="community/open_search">
	<link rel="icon" type="image/png" href="favicon.png">

	<!-- Meta Tags -->
	<meta name="generator" content="Addictive Community <?php echo VERSION ?>">
	<meta name="description" content="<?php __($meta_description) ?>">

	<!-- CSS Files -->
	<link rel="stylesheet" href="thirdparty/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" href="thirdparty/fancybox/jquery.fancybox.css">
	<link rel="stylesheet" href="thirdparty/select2/css/select2.min.css">
	<link rel="stylesheet" href="static/css/framework.css">
	<link rel="stylesheet" href="static/css/wireframe.css">
	<link rel="stylesheet" href="themes/<?php __($theme) ?>/css/theme.css">

	<?php echo $this->head ?>

	<script>
		var ROOT = "<?php echo $community_url ?>";
		var EMOTICON_DIR = "<?php echo $emoticon_dir ?>";
		var EMOTICONS = [
			<?php
				$row = [];
				foreach($emoticon_set as $emoticon) {
					$row[] = "[" . implode(", ", $emoticon) . "]";
				}

				echo implode(",\n", $row);
			?>
		];
	</script>
</head>
<body>

<header>
	<div class="top-half outer">
		<div class="row space-between">
			<div class="col-flexible text-right">
				<?php if($is_admin): ?>
					<a href="admin/" target="_blank"><span>Admin CP</span><i class="fa fa-lock"></i></a>
				<?php endif; ?>
				<a href="search"><span><?php __("SEARCH") ?></span><i class="fa fa-search"></i></a>
				<a href="members"><span><?php __("MEMBERLIST") ?></span><i class="fa fa-users"></i></a>
				<a href="calendar"><span><?php __("CALENDAR") ?></span><i class="fa fa-calendar"></i></a>
				<?php if($member_id == 0): ?>
					<a href="register"><span><?php __("SIDEBAR_C_ACCOUNT") ?></span><i class="fa fa-star"></i></a>
				<?php endif; ?>
			</div>
			<div class="col-flexible hide-xs">
				<a href="<?php echo $website_url ?>" target="_blank"><?php echo $website_name ?></a>
			</div>
		</div>
	</div>
	<div class="bottom-half outer">
		<div class="row space-between">
			<div class="col-flexible">
				<a href="<?php echo $community_url ?>">
					<img src="themes/<?php __($theme) ?>/images/logo.svg" class="logo" alt="Addictive Community">
				</a>
			</div>
			<div class="col-flexible search hide-sm">
				<form action="search" method="get">
					<input type="text" name="q" class="form-control search-input" value="<?php echo \AC\Kernel\Http::Request("q") ?>" placeholder="<?php __("SEARCH_BOX") ?>"><!--
					--><button type="submit" class="btn btn-default search-submit">
						<i class="fa fa-search"></i>
					</button>
				</form>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<ul class="breadcrumb">
					<li><a href="">Home</a></li>
					<li>Lorem ipsum dolor</li>
				</ul>
			</div>
		</div>
	</div>
</header>

<main class="outer">
	<div class="row content-row">
		<div class="" id="sidebar">
			<div class="block sidebar">
				<?php if($member_id == 0): ?>
					<div class="block flat user-box">
						<a href="/" class="username">
							<?php __("SIDEBAR_WELCOME") ?>
						</a>
						<ul>
							<li><a href="login" class="fancybox fancybox.ajax"><?php __("SIDEBAR_LOGIN") ?></a></li>
							<li><a href="register" class="font-w600"><?php __("SIDEBAR_C_ACCOUNT") ?></a></li>
						</ul>
					</div>
				<?php else: ?>
					<div class="block flat user-box">
						<?php echo \AC\Kernel\Html::Crop($member_info['avatar'], 40, "image") ?>
						<a href="profile/<?php echo $member_info['m_id'] ?>" class="username">
							<?php __($member_info['username']) ?>
						</a>
						<ul>
							<li><a href="usercp"><?php __("SIDEBAR_USERCP") ?></a></li>
							<li><a href="messenger"><?php __("SIDEBAR_INBOX", array($unread_messages)) ?></a></li>
							<li><a href="logout"><?php __("SIDEBAR_LOGOUT") ?></a></li>
						</ul>
					</div>
				<?php endif; ?>
				<div class="panel">
					<div class="panel-title"><?php __("SIDEBAR_ROOMS") ?></div>
					<div class="panel-content">
						<ul class="rooms">
							<?php foreach($sidebar_rooms as $k => $v): ?>
								<li>
									<a href="room/<?php echo $sidebar_rooms[$k]['r_id'] ?>">
										<?php echo $sidebar_rooms[$k]['name'] ?>
										<?php if($sidebar_rooms[$k]['password']): ?>
											<span class="badge"><i class="fa fa-lock"></i></span>
										<?php else: ?>
											<span class="badge"><?php echo $sidebar_rooms[$k]['threads'] ?></span>
										<?php endif; ?>
									</a>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
				<?php if($show_members_online): ?>
					<div class="panel">
						<div class="panel-title"><?php __("SIDEBAR_MEMBERS_ONLINE") ?></div>
						<div class="panel-content body">
							<dl class="members">
								<dt><?php __("SIDEBAR_MEMBER_COUNT", array($member_count)) ?></dt>
								<dd><?php echo $member_list ?></dd>
								<dt><?php __("SIDEBAR_GUEST_COUNT", array($guests_count)) ?></dt>
							</dl>
						</div>
					</div>
				<?php endif; ?>
				<?php if($show_statistics): ?>
					<div class="panel">
						<div class="panel-title"><?php __("SIDEBAR_STATISTICS") ?></div>
						<div class="panel-content body">
							<dl class="stats">
								<dt><?php __("SIDEBAR_S_THREADS") ?></dt>
								<dd><?php echo $stats['threads'] ?></dd>
								<dt><?php __("SIDEBAR_S_POSTS") ?></dt>
								<dd><?php echo $stats['posts'] ?></dd>
								<dt><?php __("SIDEBAR_S_MEMBERS") ?></dt>
								<dd><?php echo $stats['members'] ?></dd>
								<dt><?php __("SIDEBAR_S_LAST") ?></dt>
								<dd>
									<a href="profile/<?php echo $stats['lastmemberid'] ?>">
										<?php echo $stats['lastmembername'] ?>
									</a>
								</dd>
							</dl>
						</div>
					</div>
				<?php endif; ?>
			</div>
		</div>
		<div class="" id="content">
			<?php echo $this->content ?>
		</div>
	</div>
</main>

<footer class="text-center">
	Powered by
	<a href="https://github.com/brunnopleffken/addictive-community" target="_blank">Addictive Community</a>
	<?php echo VERSION . "-" . CHANNEL ?> &copy; <?php echo date("Y") ?> - All rights reserved.
</footer>

<!-- JS -->
<script src="thirdparty/jquery/jquery.min.js"></script>
<script src="thirdparty/tinymce/tinymce.min.js"></script>
<script src="thirdparty/fancybox/jquery.fancybox.pack.js"></script>
<script src="thirdparty/select2/js/select2.full.min.js"></script>
<script src="static/js/application.js"></script>

</body>
</html>
