<!DOCTYPE html>
<html>
<head>
	<title>Addictive Community - Diagnostic Tool</title>
	<meta charset="utf-8">
	<link href="<?php echo ROOT ?>/admin/styles/admin_style.css" type="text/css" rel="stylesheet">
	<link href="<?php echo ROOT ?>/thirdparty/font-awesome/css/font-awesome.min.css" type="text/css" rel="stylesheet">
	<script src="<?php echo ROOT ?>/thirdparty/jquery/jquery.min.js"></script>
	<!-- Admin JS -->
	<script src="diagnostics.js"></script>
	<style>
		td span { color: #ccc; }
		td span.yes { color: #090; }
		td span.no { color: #c00; }
	</style>
</head>

<body>

	<div id="topbar">
		<div class="wrapper">
			<div class="fleft">
				<a href="../" target="_blank" class="toplinks transition">&laquo; Go To Admin CP</a>
			</div>
			<div class="fright"><a href="https://github.com/brunnopleffken/addictive-community" target="_blank" class="transition">View Addictive Comunity on GitHub</a></div>
			<div class="fix"></div>
		</div>
	</div>

	<div id="logo">
		<div class="wrapper">
			<a href="main.php" title="Admin CP Dashboard"><img src="<?php echo ROOT ?>/admin/images/logo.png" class="logo-image"></a>
		</div>
	</div>

	<div class="wrapper">
		<h1>Diagnostic Tool</h1>
		<div id="content">
			<?php echo \AC\Kernel\Html::Notification("Run this tool just if you have a failed installation of Addictive Community, not before, otherwise you might get obvious errors of empty database or files.", "warning"); ?>

			<table class="table-list">
				<tr>
					<th colspan='2'>Results</th>
				</tr>
				<tr class="subtitle">
					<td colspan="2">Check config.ini</td>
				</tr>
				<tr>
					<td style="width:200px">Check if configuration file exists</td>
					<td><span id="config-exists">Not tested</span></td>
				</tr>
				<tr>
					<td style="width:200px">Check if file contains any data</td>
					<td><span id="config-has-data">Not tested</span></td>
				</tr>
				<tr class="subtitle">
					<td colspan="2">Check database (MySQL) connection</td>
				</tr>
				<tr>
					<td style="width:200px">Try to connect to MySQL server</td>
					<td><span id="db-connect">Not tested</span></td>
				</tr>
				<tr>
					<td style="width:200px">Check if database exists</td>
					<td><span id="db-database">Not tested</span></td>
				</tr>
				<tr>
					<td style="width:200px">Check if tables are created</td>
					<td><span id="db-tables">Not tested</span></td>
				</tr>
				<tr class="subtitle">
					<td colspan="2">Check server environment</td>
				</tr>
				<tr>
					<td style="width:200px">Check if you're running Apache</td>
					<td><span id="env-apache">Not tested</span></td>
				</tr>
				<tr>
					<td style="width:200px">Check PHP version (>5.3)</td>
					<td><span id="env-php">Not tested</span></td>
				</tr>
				<tr>
					<td style="width:200px">Check MySQL version (>5.5)</td>
					<td><span id="env-mysql">Not tested</span></td>
				</tr>
				<tr>
					<td style="width:200px">Check if mod_rewrite is enabled</td>
					<td><span id="env-mod-rewrite">Not tested</span></td>
				</tr>
			</table>

			<div id="everything-ok" style="display: none">
				<h3>Everything seems to be OK. If you're experiencing any problem, feel free to <a href="https://github.com/brunnopleffken/addictive-community/issues">report it on GitHub</a>.
				<br>For security reasons, your installer were locked again. To rerun the Diagnostic Tool, delete the file "installer/.lock" again.</h3>
			</div>
			<br>
			<p>When <a href="https://github.com/brunnopleffken/addictive-community/issues/new">opening a new issue report</a>, please, copy and paste the information below (it doesn't contain sensitive information):</p>
			<br>
			<textarea rows="15" style="width: 800px; font-family: monospace; font-size: 11px" onclick="this.select()" readonly>ADDICTIVE COMMUNITY AND SERVER INFO
- Software version: Addictive Community <?php echo VERSION ?>;
- Server software: <?php echo $_SERVER['SERVER_SOFTWARE'] ?>;
- PHP version: <?php echo PHP_VERSION ?>;

APACHE MODULES
<?php echo implode(apache_get_modules(), ", ") ?>;

PHP LOADED EXTENSIONS
<?php echo implode(get_loaded_extensions(), ", ") ?>;</textarea>
		</div>
	</div>

	<div id="footer">
		<div class="wrapper center">
			<span>Powered by Addictive Community &copy; 2014 - All rights reserved.</span>
		</div>
	</div>

</body>
</html>
